UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 38.8, sas.DateModification = NOW() where sas.RefPrestashop = 12 ;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 38.37, sas.DateModification = NOW() where sas.RefPrestashop = 15 ;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 34.53, sas.DateModification = NOW() where sas.RefPrestashop = 16 ;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 4.94, sas.DateModification = NOW() where sas.RefPrestashop = 56 ;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 4.18, sas.DateModification = NOW() where sas.RefPrestashop = 58 ;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 32.48, sas.DateModification = NOW() where sas.RefPrestashop = 63 ;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 55.83, sas.DateModification = NOW() where sas.RefPrestashop = 64 ;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 165, sas.DateModification = NOW() where sas.RefPrestashop = 96 ;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 4.87, sas.DateModification = NOW() where sas.RefPrestashop = 97 ;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 4.94, sas.DateModification = NOW() where sas.RefPrestashop = 98 ;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 97.13, sas.DateModification = NOW() where sas.RefPrestashop = 99 ;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 111.83, sas.DateModification = NOW() where sas.RefPrestashop = 100 ;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 182.76, sas.DateModification = NOW() where sas.RefPrestashop = 114 ;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 124, sas.DateModification = NOW() where sas.RefPrestashop = 115 ;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 168, sas.DateModification = NOW() where sas.RefPrestashop = 116 ;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 54, sas.DateModification = NOW() where sas.RefPrestashop = 118 ;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 715, sas.DateModification = NOW() where sas.RefPrestashop = 121 ;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 187, sas.DateModification = NOW() where sas.RefPrestashop = 124 ;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 107.62, sas.DateModification = NOW() where sas.RefPrestashop = 125 ;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 71.05, sas.DateModification = NOW() where sas.RefPrestashop = 126 ;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 100.31, sas.DateModification = NOW() where sas.RefPrestashop = 127 ;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 6.34, sas.DateModification = NOW() where sas.RefPrestashop = 131 ;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 47.94, sas.DateModification = NOW() where sas.RefPrestashop = 137 ;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 594.83, sas.DateModification = NOW() where sas.RefPrestashop = 138 ;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 640.38, sas.DateModification = NOW() where sas.RefPrestashop = 139 ;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 41.1, sas.DateModification = NOW() where sas.RefPrestashop = 140 ;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 3811.14, sas.DateModification = NOW() where sas.RefPrestashop = 141 ;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 119.89, sas.DateModification = NOW() where sas.RefPrestashop = 142 ;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 138.13, sas.DateModification = NOW() where sas.RefPrestashop = 143 ;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 191.42, sas.DateModification = NOW() where sas.RefPrestashop = 144 ;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 237.1, sas.DateModification = NOW() where sas.RefPrestashop = 145 ;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 315.06, sas.DateModification = NOW() where sas.RefPrestashop = 146 ;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 431.65, sas.DateModification = NOW() where sas.RefPrestashop = 147 ;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 441.73, sas.DateModification = NOW() where sas.RefPrestashop = 148 ;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 16.5, sas.DateModification = NOW() where sas.RefPrestashop = 188 ;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 12.1, sas.DateModification = NOW() where sas.RefPrestashop = 189 ;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 9.9, sas.DateModification = NOW() where sas.RefPrestashop = 190 ;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 3.77, sas.DateModification = NOW() where sas.RefPrestashop = 445 ;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 10.26, sas.DateModification = NOW() where sas.RefPrestashop = 447 ;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 7.44, sas.DateModification = NOW() where sas.RefPrestashop = 448 ;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 19.32, sas.DateModification = NOW() where sas.RefPrestashop = 449 ;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 120, sas.DateModification = NOW() where sas.RefPrestashop = 450 ;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 1.1, sas.DateModification = NOW() where sas.RefPrestashop = 453 ;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 524.71, sas.DateModification = NOW() where sas.RefPrestashop = 459 ;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 59.85, sas.DateModification = NOW() where sas.RefPrestashop = 463 ;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 2.25, sas.DateModification = NOW() where sas.RefPrestashop = 466 ;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 1.87, sas.DateModification = NOW() where sas.RefPrestashop = 467 ;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 2.91, sas.DateModification = NOW() where sas.RefPrestashop = 468 ;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 2.56, sas.DateModification = NOW() where sas.RefPrestashop = 469 ;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 86.26, sas.DateModification = NOW() where sas.RefPrestashop = 479 ;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 0.97, sas.DateModification = NOW() where sas.RefPrestashop = 483 ;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 1.77, sas.DateModification = NOW() where sas.RefPrestashop = 484 ;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 1.02, sas.DateModification = NOW() where sas.RefPrestashop = 485 ;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 9.43, sas.DateModification = NOW() where sas.RefPrestashop = 487 ;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 25.14, sas.DateModification = NOW() where sas.RefPrestashop = 508 ;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 2.25, sas.DateModification = NOW() where sas.RefPrestashop = 512 ;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 1.87, sas.DateModification = NOW() where sas.RefPrestashop = 513 ;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 2.31, sas.DateModification = NOW() where sas.RefPrestashop = 514 ;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 2.31, sas.DateModification = NOW() where sas.RefPrestashop = 515 ;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 3.54, sas.DateModification = NOW() where sas.RefPrestashop = 516 ;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 2.85, sas.DateModification = NOW() where sas.RefPrestashop = 517 ;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 11.02, sas.DateModification = NOW() where sas.RefPrestashop = 518 ;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 11.03, sas.DateModification = NOW() where sas.RefPrestashop = 519 ;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 1.34, sas.DateModification = NOW() where sas.RefPrestashop = 520 ;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 3.44, sas.DateModification = NOW() where sas.RefPrestashop = 522 ;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 3.22, sas.DateModification = NOW() where sas.RefPrestashop = 523 ;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 24.03, sas.DateModification = NOW() where sas.RefPrestashop = 524 ;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 1.18, sas.DateModification = NOW() where sas.RefPrestashop = 527 ;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 8.23, sas.DateModification = NOW() where sas.RefPrestashop = 538 ;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 139.17, sas.DateModification = NOW() where sas.RefPrestashop = 548 ;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 11.27, sas.DateModification = NOW() where sas.RefPrestashop = 549 ;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 13.19, sas.DateModification = NOW() where sas.RefPrestashop = 550 ;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 13.19, sas.DateModification = NOW() where sas.RefPrestashop = 551 ;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 29.78, sas.DateModification = NOW() where sas.RefPrestashop = 552 ;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 90.27, sas.DateModification = NOW() where sas.RefPrestashop = 559 ;

UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 320, sas.DateModification = NOW() where sas.RefPrestashop = 18 and sas.id_product_attribute = 2495;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 387, sas.DateModification = NOW() where sas.RefPrestashop = 18 and sas.id_product_attribute = 2496;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 467, sas.DateModification = NOW() where sas.RefPrestashop = 18 and sas.id_product_attribute = 2497;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 517, sas.DateModification = NOW() where sas.RefPrestashop = 18 and sas.id_product_attribute = 2498;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 616, sas.DateModification = NOW() where sas.RefPrestashop = 18 and sas.id_product_attribute = 2499;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 595, sas.DateModification = NOW() where sas.RefPrestashop = 18 and sas.id_product_attribute = 2500;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 616, sas.DateModification = NOW() where sas.RefPrestashop = 18 and sas.id_product_attribute = 2502;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 763, sas.DateModification = NOW() where sas.RefPrestashop = 18 and sas.id_product_attribute = 2503;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 744, sas.DateModification = NOW() where sas.RefPrestashop = 18 and sas.id_product_attribute = 2504;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 763, sas.DateModification = NOW() where sas.RefPrestashop = 18 and sas.id_product_attribute = 2505;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 862, sas.DateModification = NOW() where sas.RefPrestashop = 18 and sas.id_product_attribute = 2506;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 770, sas.DateModification = NOW() where sas.RefPrestashop = 18 and sas.id_product_attribute = 2507;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 826, sas.DateModification = NOW() where sas.RefPrestashop = 18 and sas.id_product_attribute = 2508;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 912, sas.DateModification = NOW() where sas.RefPrestashop = 18 and sas.id_product_attribute = 2509;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 986, sas.DateModification = NOW() where sas.RefPrestashop = 18 and sas.id_product_attribute = 2510;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 1117, sas.DateModification = NOW() where sas.RefPrestashop = 18 and sas.id_product_attribute = 2511;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 986, sas.DateModification = NOW() where sas.RefPrestashop = 18 and sas.id_product_attribute = 2512;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 1225, sas.DateModification = NOW() where sas.RefPrestashop = 18 and sas.id_product_attribute = 2513;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 1375, sas.DateModification = NOW() where sas.RefPrestashop = 18 and sas.id_product_attribute = 2514;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 1408, sas.DateModification = NOW() where sas.RefPrestashop = 18 and sas.id_product_attribute = 2515;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 1520, sas.DateModification = NOW() where sas.RefPrestashop = 18 and sas.id_product_attribute = 2516;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 1525, sas.DateModification = NOW() where sas.RefPrestashop = 18 and sas.id_product_attribute = 2517;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 0.8, sas.DateModification = NOW() where sas.RefPrestashop = 27 and sas.id_product_attribute = 446;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 1.29, sas.DateModification = NOW() where sas.RefPrestashop = 27 and sas.id_product_attribute = 447;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 204, sas.DateModification = NOW() where sas.RefPrestashop = 29 and sas.id_product_attribute = 372;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 254, sas.DateModification = NOW() where sas.RefPrestashop = 29 and sas.id_product_attribute = 373;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 257, sas.DateModification = NOW() where sas.RefPrestashop = 29 and sas.id_product_attribute = 374;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 305, sas.DateModification = NOW() where sas.RefPrestashop = 29 and sas.id_product_attribute = 375;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 416, sas.DateModification = NOW() where sas.RefPrestashop = 29 and sas.id_product_attribute = 376;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 455, sas.DateModification = NOW() where sas.RefPrestashop = 29 and sas.id_product_attribute = 377;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 520, sas.DateModification = NOW() where sas.RefPrestashop = 29 and sas.id_product_attribute = 378;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 548, sas.DateModification = NOW() where sas.RefPrestashop = 29 and sas.id_product_attribute = 379;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 622, sas.DateModification = NOW() where sas.RefPrestashop = 29 and sas.id_product_attribute = 380;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 727, sas.DateModification = NOW() where sas.RefPrestashop = 29 and sas.id_product_attribute = 381;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 765, sas.DateModification = NOW() where sas.RefPrestashop = 29 and sas.id_product_attribute = 382;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 877, sas.DateModification = NOW() where sas.RefPrestashop = 29 and sas.id_product_attribute = 383;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 1101, sas.DateModification = NOW() where sas.RefPrestashop = 29 and sas.id_product_attribute = 384;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 1141, sas.DateModification = NOW() where sas.RefPrestashop = 29 and sas.id_product_attribute = 385;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 761, sas.DateModification = NOW() where sas.RefPrestashop = 122 and sas.id_product_attribute = 2456;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 764, sas.DateModification = NOW() where sas.RefPrestashop = 122 and sas.id_product_attribute = 2457;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 15.96, sas.DateModification = NOW() where sas.RefPrestashop = 149 and sas.id_product_attribute = 466;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 17.26, sas.DateModification = NOW() where sas.RefPrestashop = 149 and sas.id_product_attribute = 467;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 383.28, sas.DateModification = NOW() where sas.RefPrestashop = 151 and sas.id_product_attribute = 339;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 413.77, sas.DateModification = NOW() where sas.RefPrestashop = 151 and sas.id_product_attribute = 340;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 476.24, sas.DateModification = NOW() where sas.RefPrestashop = 151 and sas.id_product_attribute = 341;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 518.4, sas.DateModification = NOW() where sas.RefPrestashop = 151 and sas.id_product_attribute = 342;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 0.0557, sas.DateModification = NOW() where sas.RefPrestashop = 153 and sas.id_product_attribute = 417;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 0.078, sas.DateModification = NOW() where sas.RefPrestashop = 153 and sas.id_product_attribute = 419;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 0.1114, sas.DateModification = NOW() where sas.RefPrestashop = 153 and sas.id_product_attribute = 422;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 0.1392, sas.DateModification = NOW() where sas.RefPrestashop = 153 and sas.id_product_attribute = 425;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 0.1672, sas.DateModification = NOW() where sas.RefPrestashop = 153 and sas.id_product_attribute = 428;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 0.2004, sas.DateModification = NOW() where sas.RefPrestashop = 153 and sas.id_product_attribute = 429;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 0.2229, sas.DateModification = NOW() where sas.RefPrestashop = 153 and sas.id_product_attribute = 430;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 0.2786, sas.DateModification = NOW() where sas.RefPrestashop = 153 and sas.id_product_attribute = 431;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 1018, sas.DateModification = NOW() where sas.RefPrestashop = 154 and sas.id_product_attribute = 2367;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 1192, sas.DateModification = NOW() where sas.RefPrestashop = 154 and sas.id_product_attribute = 2368;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 2036, sas.DateModification = NOW() where sas.RefPrestashop = 154 and sas.id_product_attribute = 2369;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 2383, sas.DateModification = NOW() where sas.RefPrestashop = 154 and sas.id_product_attribute = 2370;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 4072, sas.DateModification = NOW() where sas.RefPrestashop = 154 and sas.id_product_attribute = 2371;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 4766, sas.DateModification = NOW() where sas.RefPrestashop = 154 and sas.id_product_attribute = 2372;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 8144, sas.DateModification = NOW() where sas.RefPrestashop = 154 and sas.id_product_attribute = 2373;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 247, sas.DateModification = NOW() where sas.RefPrestashop = 158 and sas.id_product_attribute = 2518;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 317, sas.DateModification = NOW() where sas.RefPrestashop = 158 and sas.id_product_attribute = 2519;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 374, sas.DateModification = NOW() where sas.RefPrestashop = 158 and sas.id_product_attribute = 2520;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 504, sas.DateModification = NOW() where sas.RefPrestashop = 158 and sas.id_product_attribute = 2521;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 644, sas.DateModification = NOW() where sas.RefPrestashop = 158 and sas.id_product_attribute = 2522;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 562, sas.DateModification = NOW() where sas.RefPrestashop = 158 and sas.id_product_attribute = 2523;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 692, sas.DateModification = NOW() where sas.RefPrestashop = 158 and sas.id_product_attribute = 2524;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 750, sas.DateModification = NOW() where sas.RefPrestashop = 158 and sas.id_product_attribute = 2525;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 880, sas.DateModification = NOW() where sas.RefPrestashop = 158 and sas.id_product_attribute = 2526;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 1116, sas.DateModification = NOW() where sas.RefPrestashop = 158 and sas.id_product_attribute = 2527;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 1272, sas.DateModification = NOW() where sas.RefPrestashop = 158 and sas.id_product_attribute = 2528;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 1183, sas.DateModification = NOW() where sas.RefPrestashop = 158 and sas.id_product_attribute = 2529;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 1473, sas.DateModification = NOW() where sas.RefPrestashop = 158 and sas.id_product_attribute = 2530;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 1588, sas.DateModification = NOW() where sas.RefPrestashop = 158 and sas.id_product_attribute = 2531;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 1796, sas.DateModification = NOW() where sas.RefPrestashop = 158 and sas.id_product_attribute = 2532;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 876, sas.DateModification = NOW() where sas.RefPrestashop = 158 and sas.id_product_attribute = 2533;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 748, sas.DateModification = NOW() where sas.RefPrestashop = 158 and sas.id_product_attribute = 2534;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 1068, sas.DateModification = NOW() where sas.RefPrestashop = 158 and sas.id_product_attribute = 2535;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 1690, sas.DateModification = NOW() where sas.RefPrestashop = 158 and sas.id_product_attribute = 2536;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 1886, sas.DateModification = NOW() where sas.RefPrestashop = 158 and sas.id_product_attribute = 2537;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 0.46, sas.DateModification = NOW() where sas.RefPrestashop = 440 and sas.id_product_attribute = 450;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 0.92, sas.DateModification = NOW() where sas.RefPrestashop = 440 and sas.id_product_attribute = 451;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 0.64, sas.DateModification = NOW() where sas.RefPrestashop = 441 and sas.id_product_attribute = 453;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 0.91, sas.DateModification = NOW() where sas.RefPrestashop = 441 and sas.id_product_attribute = 454;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 0.4, sas.DateModification = NOW() where sas.RefPrestashop = 442 and sas.id_product_attribute = 456;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 0.78, sas.DateModification = NOW() where sas.RefPrestashop = 442 and sas.id_product_attribute = 457;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 8.38, sas.DateModification = NOW() where sas.RefPrestashop = 465 and sas.id_product_attribute = 534;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 10.77, sas.DateModification = NOW() where sas.RefPrestashop = 465 and sas.id_product_attribute = 535;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 505.5, sas.DateModification = NOW() where sas.RefPrestashop = 511 and sas.id_product_attribute = 2474;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 635, sas.DateModification = NOW() where sas.RefPrestashop = 511 and sas.id_product_attribute = 2475;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 785, sas.DateModification = NOW() where sas.RefPrestashop = 511 and sas.id_product_attribute = 2476;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 892, sas.DateModification = NOW() where sas.RefPrestashop = 511 and sas.id_product_attribute = 2477;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 1121, sas.DateModification = NOW() where sas.RefPrestashop = 511 and sas.id_product_attribute = 2478;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 1239, sas.DateModification = NOW() where sas.RefPrestashop = 511 and sas.id_product_attribute = 2479;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 1178, sas.DateModification = NOW() where sas.RefPrestashop = 511 and sas.id_product_attribute = 2480;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 1456, sas.DateModification = NOW() where sas.RefPrestashop = 511 and sas.id_product_attribute = 2481;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 1621, sas.DateModification = NOW() where sas.RefPrestashop = 511 and sas.id_product_attribute = 2482;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 1513, sas.DateModification = NOW() where sas.RefPrestashop = 511 and sas.id_product_attribute = 2483;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 1643, sas.DateModification = NOW() where sas.RefPrestashop = 511 and sas.id_product_attribute = 2484;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 2028, sas.DateModification = NOW() where sas.RefPrestashop = 511 and sas.id_product_attribute = 2485;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 2388, sas.DateModification = NOW() where sas.RefPrestashop = 511 and sas.id_product_attribute = 2486;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 2698, sas.DateModification = NOW() where sas.RefPrestashop = 511 and sas.id_product_attribute = 2487;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 2813, sas.DateModification = NOW() where sas.RefPrestashop = 511 and sas.id_product_attribute = 2488;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 3035, sas.DateModification = NOW() where sas.RefPrestashop = 511 and sas.id_product_attribute = 2489;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 1573, sas.DateModification = NOW() where sas.RefPrestashop = 511 and sas.id_product_attribute = 2490;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 2054, sas.DateModification = NOW() where sas.RefPrestashop = 511 and sas.id_product_attribute = 2491;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 2169, sas.DateModification = NOW() where sas.RefPrestashop = 511 and sas.id_product_attribute = 2492;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 2898, sas.DateModification = NOW() where sas.RefPrestashop = 511 and sas.id_product_attribute = 2493;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 3307, sas.DateModification = NOW() where sas.RefPrestashop = 511 and sas.id_product_attribute = 2494;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 10.28, sas.DateModification = NOW() where sas.RefPrestashop = 526 and sas.id_product_attribute = 724;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 8.18, sas.DateModification = NOW() where sas.RefPrestashop = 526 and sas.id_product_attribute = 725;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 884.97, sas.DateModification = NOW() where sas.RefPrestashop = 532 and sas.id_product_attribute = 896;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 978.97, sas.DateModification = NOW() where sas.RefPrestashop = 532 and sas.id_product_attribute = 897;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 889.52, sas.DateModification = NOW() where sas.RefPrestashop = 532 and sas.id_product_attribute = 898;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 997.44, sas.DateModification = NOW() where sas.RefPrestashop = 532 and sas.id_product_attribute = 899;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 937.89, sas.DateModification = NOW() where sas.RefPrestashop = 532 and sas.id_product_attribute = 900;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 1043.23, sas.DateModification = NOW() where sas.RefPrestashop = 532 and sas.id_product_attribute = 901;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 966.1, sas.DateModification = NOW() where sas.RefPrestashop = 532 and sas.id_product_attribute = 906;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 1087.29, sas.DateModification = NOW() where sas.RefPrestashop = 532 and sas.id_product_attribute = 907;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 964.56, sas.DateModification = NOW() where sas.RefPrestashop = 532 and sas.id_product_attribute = 908;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 1095.27, sas.DateModification = NOW() where sas.RefPrestashop = 532 and sas.id_product_attribute = 909;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 1038.25, sas.DateModification = NOW() where sas.RefPrestashop = 532 and sas.id_product_attribute = 910;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 1143.9, sas.DateModification = NOW() where sas.RefPrestashop = 532 and sas.id_product_attribute = 911;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 979.1, sas.DateModification = NOW() where sas.RefPrestashop = 532 and sas.id_product_attribute = 916;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 1093.16, sas.DateModification = NOW() where sas.RefPrestashop = 532 and sas.id_product_attribute = 917;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 994.44, sas.DateModification = NOW() where sas.RefPrestashop = 532 and sas.id_product_attribute = 918;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 1106.28, sas.DateModification = NOW() where sas.RefPrestashop = 532 and sas.id_product_attribute = 919;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 1048.32, sas.DateModification = NOW() where sas.RefPrestashop = 532 and sas.id_product_attribute = 920;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 1145.32, sas.DateModification = NOW() where sas.RefPrestashop = 532 and sas.id_product_attribute = 921;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 1248.66, sas.DateModification = NOW() where sas.RefPrestashop = 532 and sas.id_product_attribute = 937;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 1348.01, sas.DateModification = NOW() where sas.RefPrestashop = 532 and sas.id_product_attribute = 939;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 1343.64, sas.DateModification = NOW() where sas.RefPrestashop = 532 and sas.id_product_attribute = 941;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 7.83, sas.DateModification = NOW() where sas.RefPrestashop = 536 and sas.id_product_attribute = 933;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 10.35, sas.DateModification = NOW() where sas.RefPrestashop = 536 and sas.id_product_attribute = 934;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 838.6, sas.DateModification = NOW() where sas.RefPrestashop = 558 and sas.id_product_attribute = 2335;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 838.67, sas.DateModification = NOW() where sas.RefPrestashop = 558 and sas.id_product_attribute = 2336;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 1064, sas.DateModification = NOW() where sas.RefPrestashop = 558 and sas.id_product_attribute = 2337;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 1182, sas.DateModification = NOW() where sas.RefPrestashop = 558 and sas.id_product_attribute = 2338;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 1297, sas.DateModification = NOW() where sas.RefPrestashop = 558 and sas.id_product_attribute = 2339;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 1328, sas.DateModification = NOW() where sas.RefPrestashop = 558 and sas.id_product_attribute = 2340;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 1412, sas.DateModification = NOW() where sas.RefPrestashop = 558 and sas.id_product_attribute = 2341;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 1475, sas.DateModification = NOW() where sas.RefPrestashop = 558 and sas.id_product_attribute = 2342;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 1622, sas.DateModification = NOW() where sas.RefPrestashop = 558 and sas.id_product_attribute = 2343;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 1814, sas.DateModification = NOW() where sas.RefPrestashop = 558 and sas.id_product_attribute = 2344;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 1933, sas.DateModification = NOW() where sas.RefPrestashop = 558 and sas.id_product_attribute = 2345;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 2066, sas.DateModification = NOW() where sas.RefPrestashop = 558 and sas.id_product_attribute = 2346;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 1947, sas.DateModification = NOW() where sas.RefPrestashop = 558 and sas.id_product_attribute = 2347;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 2342, sas.DateModification = NOW() where sas.RefPrestashop = 558 and sas.id_product_attribute = 2348;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 2430, sas.DateModification = NOW() where sas.RefPrestashop = 558 and sas.id_product_attribute = 2349;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 2543, sas.DateModification = NOW() where sas.RefPrestashop = 558 and sas.id_product_attribute = 2350;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 0.74, sas.DateModification = NOW() where sas.RefPrestashop = 560 and sas.id_product_attribute = 1514;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 0.98, sas.DateModification = NOW() where sas.RefPrestashop = 560 and sas.id_product_attribute = 1516;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 1.23, sas.DateModification = NOW() where sas.RefPrestashop = 560 and sas.id_product_attribute = 1517;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 0.66, sas.DateModification = NOW() where sas.RefPrestashop = 560 and sas.id_product_attribute = 2553;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 35, sas.DateModification = NOW() where sas.RefPrestashop = 562 and sas.id_product_attribute = 1550;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 35, sas.DateModification = NOW() where sas.RefPrestashop = 562 and sas.id_product_attribute = 1551;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 40, sas.DateModification = NOW() where sas.RefPrestashop = 562 and sas.id_product_attribute = 1552;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 51, sas.DateModification = NOW() where sas.RefPrestashop = 562 and sas.id_product_attribute = 1553;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 40, sas.DateModification = NOW() where sas.RefPrestashop = 562 and sas.id_product_attribute = 1554;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 61, sas.DateModification = NOW() where sas.RefPrestashop = 562 and sas.id_product_attribute = 1555;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 70, sas.DateModification = NOW() where sas.RefPrestashop = 562 and sas.id_product_attribute = 1556;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 71, sas.DateModification = NOW() where sas.RefPrestashop = 562 and sas.id_product_attribute = 1557;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 86, sas.DateModification = NOW() where sas.RefPrestashop = 562 and sas.id_product_attribute = 1558;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 100, sas.DateModification = NOW() where sas.RefPrestashop = 562 and sas.id_product_attribute = 1559;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 51, sas.DateModification = NOW() where sas.RefPrestashop = 562 and sas.id_product_attribute = 1560;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 94, sas.DateModification = NOW() where sas.RefPrestashop = 562 and sas.id_product_attribute = 1561;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 100, sas.DateModification = NOW() where sas.RefPrestashop = 562 and sas.id_product_attribute = 1562;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 100, sas.DateModification = NOW() where sas.RefPrestashop = 562 and sas.id_product_attribute = 1563;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 105, sas.DateModification = NOW() where sas.RefPrestashop = 562 and sas.id_product_attribute = 1564;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 115, sas.DateModification = NOW() where sas.RefPrestashop = 562 and sas.id_product_attribute = 1565;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 697, sas.DateModification = NOW() where sas.RefPrestashop = 563 and sas.id_product_attribute = 2351;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 892.5, sas.DateModification = NOW() where sas.RefPrestashop = 563 and sas.id_product_attribute = 2352;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 959, sas.DateModification = NOW() where sas.RefPrestashop = 563 and sas.id_product_attribute = 2353;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 1107, sas.DateModification = NOW() where sas.RefPrestashop = 563 and sas.id_product_attribute = 2354;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 1202, sas.DateModification = NOW() where sas.RefPrestashop = 563 and sas.id_product_attribute = 2355;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 1240, sas.DateModification = NOW() where sas.RefPrestashop = 563 and sas.id_product_attribute = 2356;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 1312, sas.DateModification = NOW() where sas.RefPrestashop = 563 and sas.id_product_attribute = 2357;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 1375, sas.DateModification = NOW() where sas.RefPrestashop = 563 and sas.id_product_attribute = 2358;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 1508, sas.DateModification = NOW() where sas.RefPrestashop = 563 and sas.id_product_attribute = 2359;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 1716, sas.DateModification = NOW() where sas.RefPrestashop = 563 and sas.id_product_attribute = 2360;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 1860, sas.DateModification = NOW() where sas.RefPrestashop = 563 and sas.id_product_attribute = 2361;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 1976, sas.DateModification = NOW() where sas.RefPrestashop = 563 and sas.id_product_attribute = 2362;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 1840, sas.DateModification = NOW() where sas.RefPrestashop = 563 and sas.id_product_attribute = 2363;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 2251, sas.DateModification = NOW() where sas.RefPrestashop = 563 and sas.id_product_attribute = 2364;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 2328, sas.DateModification = NOW() where sas.RefPrestashop = 563 and sas.id_product_attribute = 2365;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 2425, sas.DateModification = NOW() where sas.RefPrestashop = 563 and sas.id_product_attribute = 2366;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 769.5, sas.DateModification = NOW() where sas.RefPrestashop = 571 and sas.id_product_attribute = 2444;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 1539, sas.DateModification = NOW() where sas.RefPrestashop = 571 and sas.id_product_attribute = 2445;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 57.5, sas.DateModification = NOW() where sas.RefPrestashop = 572 and sas.id_product_attribute = 2446;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 110, sas.DateModification = NOW() where sas.RefPrestashop = 572 and sas.id_product_attribute = 2447;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 29.75, sas.DateModification = NOW() where sas.RefPrestashop = 572 and sas.id_product_attribute = 2449;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 165, sas.DateModification = NOW() where sas.RefPrestashop = 574 and sas.id_product_attribute = 2452;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 82.5, sas.DateModification = NOW() where sas.RefPrestashop = 574 and sas.id_product_attribute = 2453;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 0.69, sas.DateModification = NOW() where sas.RefPrestashop = 577 and sas.id_product_attribute = 2538;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 0.64, sas.DateModification = NOW() where sas.RefPrestashop = 577 and sas.id_product_attribute = 2539;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 0.61, sas.DateModification = NOW() where sas.RefPrestashop = 577 and sas.id_product_attribute = 2540;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 0.59, sas.DateModification = NOW() where sas.RefPrestashop = 577 and sas.id_product_attribute = 2554;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 2263.86, sas.DateModification = NOW() where sas.RefPrestashop = 578 and sas.id_product_attribute = 2561;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 2797.17, sas.DateModification = NOW() where sas.RefPrestashop = 578 and sas.id_product_attribute = 2562;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 3018.48, sas.DateModification = NOW() where sas.RefPrestashop = 578 and sas.id_product_attribute = 2563;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 3729.56, sas.DateModification = NOW() where sas.RefPrestashop = 578 and sas.id_product_attribute = 2564;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 3773.09, sas.DateModification = NOW() where sas.RefPrestashop = 578 and sas.id_product_attribute = 2565;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 4661.95, sas.DateModification = NOW() where sas.RefPrestashop = 578 and sas.id_product_attribute = 2566;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 4527.71, sas.DateModification = NOW() where sas.RefPrestashop = 578 and sas.id_product_attribute = 2567;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 5594.34, sas.DateModification = NOW() where sas.RefPrestashop = 578 and sas.id_product_attribute = 2568;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 6036.95, sas.DateModification = NOW() where sas.RefPrestashop = 578 and sas.id_product_attribute = 2569;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 7459.12, sas.DateModification = NOW() where sas.RefPrestashop = 578 and sas.id_product_attribute = 2570;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 7546.19, sas.DateModification = NOW() where sas.RefPrestashop = 578 and sas.id_product_attribute = 2571;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 9323.9, sas.DateModification = NOW() where sas.RefPrestashop = 578 and sas.id_product_attribute = 2572;




