UPDATE saskitps_product p set p.price = 49, p.date_upd=now() where p.id_product = 12 ;
UPDATE saskitps_product_shop p set p.price = 49, p.date_upd=now() where p.id_product = 12 ;
UPDATE saskitps_product p set p.price = 21.32, p.date_upd=now() where p.id_product = 14 ;
UPDATE saskitps_product_shop p set p.price = 21.32, p.date_upd=now() where p.id_product = 14 ;
UPDATE saskitps_product p set p.price = 4.26, p.date_upd=now() where p.id_product = 58 ;
UPDATE saskitps_product_shop p set p.price = 4.26, p.date_upd=now() where p.id_product = 58 ;
UPDATE saskitps_product p set p.price = 4.73, p.date_upd=now() where p.id_product = 59 ;
UPDATE saskitps_product_shop p set p.price = 4.73, p.date_upd=now() where p.id_product = 59 ;
UPDATE saskitps_product p set p.price = 24.83, p.date_upd=now() where p.id_product = 62 ;
UPDATE saskitps_product_shop p set p.price = 24.83, p.date_upd=now() where p.id_product = 62 ;
UPDATE saskitps_product p set p.price = 98.54, p.date_upd=now() where p.id_product = 99 ;
UPDATE saskitps_product_shop p set p.price = 98.54, p.date_upd=now() where p.id_product = 99 ;
UPDATE saskitps_product p set p.price = 114.74, p.date_upd=now() where p.id_product = 100 ;
UPDATE saskitps_product_shop p set p.price = 114.74, p.date_upd=now() where p.id_product = 100 ;
UPDATE saskitps_product p set p.price = 90.89, p.date_upd=now() where p.id_product = 103 ;
UPDATE saskitps_product_shop p set p.price = 90.89, p.date_upd=now() where p.id_product = 103 ;
UPDATE saskitps_product p set p.price = 35.66, p.date_upd=now() where p.id_product = 104 ;
UPDATE saskitps_product_shop p set p.price = 35.66, p.date_upd=now() where p.id_product = 104 ;
UPDATE saskitps_product p set p.price = 200.71, p.date_upd=now() where p.id_product = 113 ;
UPDATE saskitps_product_shop p set p.price = 200.71, p.date_upd=now() where p.id_product = 113 ;
UPDATE saskitps_product p set p.price = 185.05, p.date_upd=now() where p.id_product = 114 ;
UPDATE saskitps_product_shop p set p.price = 185.05, p.date_upd=now() where p.id_product = 114 ;
UPDATE saskitps_product p set p.price = 53.8, p.date_upd=now() where p.id_product = 118 ;
UPDATE saskitps_product_shop p set p.price = 53.8, p.date_upd=now() where p.id_product = 118 ;
UPDATE saskitps_product p set p.price = 200.61, p.date_upd=now() where p.id_product = 120 ;
UPDATE saskitps_product_shop p set p.price = 200.61, p.date_upd=now() where p.id_product = 120 ;
UPDATE saskitps_product p set p.price = 759.15, p.date_upd=now() where p.id_product = 121 ;
UPDATE saskitps_product_shop p set p.price = 759.15, p.date_upd=now() where p.id_product = 121 ;
UPDATE saskitps_product p set p.price = 136.32, p.date_upd=now() where p.id_product = 123 ;
UPDATE saskitps_product_shop p set p.price = 136.32, p.date_upd=now() where p.id_product = 123 ;
UPDATE saskitps_product p set p.price = 187.76, p.date_upd=now() where p.id_product = 124 ;
UPDATE saskitps_product_shop p set p.price = 187.76, p.date_upd=now() where p.id_product = 124 ;
UPDATE saskitps_product p set p.price = 6.37, p.date_upd=now() where p.id_product = 131 ;
UPDATE saskitps_product_shop p set p.price = 6.37, p.date_upd=now() where p.id_product = 131 ;
UPDATE saskitps_product p set p.price = 56.7, p.date_upd=now() where p.id_product = 137 ;
UPDATE saskitps_product_shop p set p.price = 56.7, p.date_upd=now() where p.id_product = 137 ;
UPDATE saskitps_product p set p.price = 639.08, p.date_upd=now() where p.id_product = 138 ;
UPDATE saskitps_product_shop p set p.price = 639.08, p.date_upd=now() where p.id_product = 138 ;
UPDATE saskitps_product p set p.price = 681.45, p.date_upd=now() where p.id_product = 139 ;
UPDATE saskitps_product_shop p set p.price = 681.45, p.date_upd=now() where p.id_product = 139 ;
UPDATE saskitps_product p set p.price = 20.78, p.date_upd=now() where p.id_product = 188 ;
UPDATE saskitps_product_shop p set p.price = 20.78, p.date_upd=now() where p.id_product = 188 ;
UPDATE saskitps_product p set p.price = 16.73, p.date_upd=now() where p.id_product = 189 ;
UPDATE saskitps_product_shop p set p.price = 16.73, p.date_upd=now() where p.id_product = 189 ;
UPDATE saskitps_product p set p.price = 13.28, p.date_upd=now() where p.id_product = 190 ;
UPDATE saskitps_product_shop p set p.price = 13.28, p.date_upd=now() where p.id_product = 190 ;
UPDATE saskitps_product p set p.price = 25.04, p.date_upd=now() where p.id_product = 193 ;
UPDATE saskitps_product_shop p set p.price = 25.04, p.date_upd=now() where p.id_product = 193 ;
UPDATE saskitps_product p set p.price = 16.66, p.date_upd=now() where p.id_product = 194 ;
UPDATE saskitps_product_shop p set p.price = 16.66, p.date_upd=now() where p.id_product = 194 ;
UPDATE saskitps_product p set p.price = 11.57, p.date_upd=now() where p.id_product = 447 ;
UPDATE saskitps_product_shop p set p.price = 11.57, p.date_upd=now() where p.id_product = 447 ;
UPDATE saskitps_product p set p.price = 120.54, p.date_upd=now() where p.id_product = 450 ;
UPDATE saskitps_product_shop p set p.price = 120.54, p.date_upd=now() where p.id_product = 450 ;
UPDATE saskitps_product p set p.price = 1.2688, p.date_upd=now() where p.id_product = 453 ;
UPDATE saskitps_product_shop p set p.price = 1.2688, p.date_upd=now() where p.id_product = 453 ;
UPDATE saskitps_product p set p.price = 526.41, p.date_upd=now() where p.id_product = 459 ;
UPDATE saskitps_product_shop p set p.price = 526.41, p.date_upd=now() where p.id_product = 459 ;
UPDATE saskitps_product p set p.price = 2.57, p.date_upd=now() where p.id_product = 466 ;
UPDATE saskitps_product_shop p set p.price = 2.57, p.date_upd=now() where p.id_product = 466 ;
UPDATE saskitps_product p set p.price = 2.01, p.date_upd=now() where p.id_product = 467 ;
UPDATE saskitps_product_shop p set p.price = 2.01, p.date_upd=now() where p.id_product = 467 ;
UPDATE saskitps_product p set p.price = 3.13, p.date_upd=now() where p.id_product = 468 ;
UPDATE saskitps_product_shop p set p.price = 3.13, p.date_upd=now() where p.id_product = 468 ;
UPDATE saskitps_product p set p.price = 2.75, p.date_upd=now() where p.id_product = 469 ;
UPDATE saskitps_product_shop p set p.price = 2.75, p.date_upd=now() where p.id_product = 469 ;
UPDATE saskitps_product p set p.price = 8.54, p.date_upd=now() where p.id_product = 470 ;
UPDATE saskitps_product_shop p set p.price = 8.54, p.date_upd=now() where p.id_product = 470 ;
UPDATE saskitps_product p set p.price = 27.15, p.date_upd=now() where p.id_product = 508 ;
UPDATE saskitps_product_shop p set p.price = 27.15, p.date_upd=now() where p.id_product = 508 ;
UPDATE saskitps_product p set p.price = 2.4, p.date_upd=now() where p.id_product = 512 ;
UPDATE saskitps_product_shop p set p.price = 2.4, p.date_upd=now() where p.id_product = 512 ;
UPDATE saskitps_product p set p.price = 2.06, p.date_upd=now() where p.id_product = 513 ;
UPDATE saskitps_product_shop p set p.price = 2.06, p.date_upd=now() where p.id_product = 513 ;
UPDATE saskitps_product p set p.price = 11.22, p.date_upd=now() where p.id_product = 518 ;
UPDATE saskitps_product_shop p set p.price = 11.22, p.date_upd=now() where p.id_product = 518 ;
UPDATE saskitps_product p set p.price = 11.21, p.date_upd=now() where p.id_product = 519 ;
UPDATE saskitps_product_shop p set p.price = 11.21, p.date_upd=now() where p.id_product = 519 ;
UPDATE saskitps_product p set p.price = 1.4338, p.date_upd=now() where p.id_product = 520 ;
UPDATE saskitps_product_shop p set p.price = 1.4338, p.date_upd=now() where p.id_product = 520 ;
UPDATE saskitps_product p set p.price = 8.05, p.date_upd=now() where p.id_product = 521 ;
UPDATE saskitps_product_shop p set p.price = 8.05, p.date_upd=now() where p.id_product = 521 ;
UPDATE saskitps_product p set p.price = 3.69, p.date_upd=now() where p.id_product = 522 ;
UPDATE saskitps_product_shop p set p.price = 3.69, p.date_upd=now() where p.id_product = 522 ;
UPDATE saskitps_product p set p.price = 3.23, p.date_upd=now() where p.id_product = 523 ;
UPDATE saskitps_product_shop p set p.price = 3.23, p.date_upd=now() where p.id_product = 523 ;
UPDATE saskitps_product p set p.price = 1.31175, p.date_upd=now() where p.id_product = 527 ;
UPDATE saskitps_product_shop p set p.price = 1.31175, p.date_upd=now() where p.id_product = 527 ;
UPDATE saskitps_product p set p.price = 20.63, p.date_upd=now() where p.id_product = 528 ;
UPDATE saskitps_product_shop p set p.price = 20.63, p.date_upd=now() where p.id_product = 528 ;
UPDATE saskitps_product p set p.price = 7.16, p.date_upd=now() where p.id_product = 530 ;
UPDATE saskitps_product_shop p set p.price = 7.16, p.date_upd=now() where p.id_product = 530 ;
UPDATE saskitps_product p set p.price = 76.63, p.date_upd=now() where p.id_product = 533 ;
UPDATE saskitps_product_shop p set p.price = 76.63, p.date_upd=now() where p.id_product = 533 ;
UPDATE saskitps_product p set p.price = 97.58, p.date_upd=now() where p.id_product = 534 ;
UPDATE saskitps_product_shop p set p.price = 97.58, p.date_upd=now() where p.id_product = 534 ;
UPDATE saskitps_product p set p.price = 2.33, p.date_upd=now() where p.id_product = 535 ;
UPDATE saskitps_product_shop p set p.price = 2.33, p.date_upd=now() where p.id_product = 535 ;
UPDATE saskitps_product p set p.price = 31.74, p.date_upd=now() where p.id_product = 537 ;
UPDATE saskitps_product_shop p set p.price = 31.74, p.date_upd=now() where p.id_product = 537 ;
UPDATE saskitps_product p set p.price = 20.81, p.date_upd=now() where p.id_product = 540 ;
UPDATE saskitps_product_shop p set p.price = 20.81, p.date_upd=now() where p.id_product = 540 ;
UPDATE saskitps_product p set p.price = 21.96, p.date_upd=now() where p.id_product = 541 ;
UPDATE saskitps_product_shop p set p.price = 21.96, p.date_upd=now() where p.id_product = 541 ;
UPDATE saskitps_product p set p.price = 27.41, p.date_upd=now() where p.id_product = 542 ;
UPDATE saskitps_product_shop p set p.price = 27.41, p.date_upd=now() where p.id_product = 542 ;
UPDATE saskitps_product p set p.price = 530.42, p.date_upd=now() where p.id_product = 546 ;
UPDATE saskitps_product_shop p set p.price = 530.42, p.date_upd=now() where p.id_product = 546 ;
UPDATE saskitps_product p set p.price = 160.2, p.date_upd=now() where p.id_product = 548 ;
UPDATE saskitps_product_shop p set p.price = 160.2, p.date_upd=now() where p.id_product = 548 ;
UPDATE saskitps_product p set p.price = 6.26, p.date_upd=now() where p.id_product = 549 ;
UPDATE saskitps_product_shop p set p.price = 6.26, p.date_upd=now() where p.id_product = 549 ;
UPDATE saskitps_product p set p.price = 923.65, p.date_upd=now() where p.id_product = 554 ;
UPDATE saskitps_product_shop p set p.price = 923.65, p.date_upd=now() where p.id_product = 554 ;
UPDATE saskitps_product p set p.price = 36.31, p.date_upd=now() where p.id_product = 561 ;
UPDATE saskitps_product_shop p set p.price = 36.31, p.date_upd=now() where p.id_product = 561 ;
UPDATE saskitps_product p set p.price = 234.81, p.date_upd=now() where p.id_product = 573 ;
UPDATE saskitps_product_shop p set p.price = 234.81, p.date_upd=now() where p.id_product = 573 ;
UPDATE saskitps_product p set p.price = 16.76, p.date_upd=now() where p.id_product = 581 ;
UPDATE saskitps_product_shop p set p.price = 16.76, p.date_upd=now() where p.id_product = 581 ;
UPDATE saskitps_product p set p.price = 86.35, p.date_upd=now() where p.id_product = 587 ;
UPDATE saskitps_product_shop p set p.price = 86.35, p.date_upd=now() where p.id_product = 587 ;
UPDATE saskitps_product p set p.price = 0.12285, p.date_upd=now() where p.id_product = 593 ;
UPDATE saskitps_product_shop p set p.price = 0.12285, p.date_upd=now() where p.id_product = 593 ;
UPDATE saskitps_product p set p.price = 0.38016, p.date_upd=now() where p.id_product = 594 ;
UPDATE saskitps_product_shop p set p.price = 0.38016, p.date_upd=now() where p.id_product = 594 ;
UPDATE saskitps_product p set p.price = 554.02, p.date_upd=now() where p.id_product = 597 ;
UPDATE saskitps_product_shop p set p.price = 554.02, p.date_upd=now() where p.id_product = 597 ;

UPDATE saskitps_product p set p.price = 339.99, p.date_upd=now() where p.id_product = 18 ;
UPDATE saskitps_product_shop p set p.price = 339.99, p.date_upd=now() where p.id_product = 18 ;
UPDATE saskitps_product p set p.price = 236.38, p.date_upd=now() where p.id_product = 29 ;
UPDATE saskitps_product_shop p set p.price = 236.38, p.date_upd=now() where p.id_product = 29 ;
UPDATE saskitps_product p set p.price = 801.52, p.date_upd=now() where p.id_product = 122 ;
UPDATE saskitps_product_shop p set p.price = 801.52, p.date_upd=now() where p.id_product = 122 ;
UPDATE saskitps_product p set p.price = 18.46, p.date_upd=now() where p.id_product = 149 ;
UPDATE saskitps_product_shop p set p.price = 18.46, p.date_upd=now() where p.id_product = 149 ;
UPDATE saskitps_product p set p.price = 389.71, p.date_upd=now() where p.id_product = 151 ;
UPDATE saskitps_product_shop p set p.price = 389.71, p.date_upd=now() where p.id_product = 151 ;
UPDATE saskitps_product p set p.price = 0.0612, p.date_upd=now() where p.id_product = 153 ;
UPDATE saskitps_product_shop p set p.price = 0.0612, p.date_upd=now() where p.id_product = 153 ;
UPDATE saskitps_product p set p.price = 1112.77, p.date_upd=now() where p.id_product = 154 ;
UPDATE saskitps_product_shop p set p.price = 1112.77, p.date_upd=now() where p.id_product = 154 ;
UPDATE saskitps_product p set p.price = 307.76, p.date_upd=now() where p.id_product = 158 ;
UPDATE saskitps_product_shop p set p.price = 307.76, p.date_upd=now() where p.id_product = 158 ;
UPDATE saskitps_product p set p.price = 0.468, p.date_upd=now() where p.id_product = 440 ;
UPDATE saskitps_product_shop p set p.price = 0.468, p.date_upd=now() where p.id_product = 440 ;
UPDATE saskitps_product p set p.price = 0.637, p.date_upd=now() where p.id_product = 441 ;
UPDATE saskitps_product_shop p set p.price = 0.637, p.date_upd=now() where p.id_product = 441 ;
UPDATE saskitps_product p set p.price = 0.4407, p.date_upd=now() where p.id_product = 442 ;
UPDATE saskitps_product_shop p set p.price = 0.4407, p.date_upd=now() where p.id_product = 442 ;
UPDATE saskitps_product p set p.price = 9.08, p.date_upd=now() where p.id_product = 465 ;
UPDATE saskitps_product_shop p set p.price = 9.08, p.date_upd=now() where p.id_product = 465 ;
UPDATE saskitps_product p set p.price = 8.51, p.date_upd=now() where p.id_product = 526 ;
UPDATE saskitps_product_shop p set p.price = 8.51, p.date_upd=now() where p.id_product = 526 ;
UPDATE saskitps_product p set p.price = 899.22, p.date_upd=now() where p.id_product = 532 ;
UPDATE saskitps_product_shop p set p.price = 899.22, p.date_upd=now() where p.id_product = 532 ;
UPDATE saskitps_product p set p.price = 863.14, p.date_upd=now() where p.id_product = 558 ;
UPDATE saskitps_product_shop p set p.price = 863.14, p.date_upd=now() where p.id_product = 558 ;
UPDATE saskitps_product p set p.price = 0.72, p.date_upd=now() where p.id_product = 560 ;
UPDATE saskitps_product_shop p set p.price = 0.72, p.date_upd=now() where p.id_product = 560 ;
UPDATE saskitps_product p set p.price = 36.67, p.date_upd=now() where p.id_product = 562 ;
UPDATE saskitps_product_shop p set p.price = 36.67, p.date_upd=now() where p.id_product = 562 ;
UPDATE saskitps_product p set p.price = 717.74, p.date_upd=now() where p.id_product = 563 ;
UPDATE saskitps_product_shop p set p.price = 717.74, p.date_upd=now() where p.id_product = 563 ;
UPDATE saskitps_product p set p.price = 32, p.date_upd=now() where p.id_product = 572 ;
UPDATE saskitps_product_shop p set p.price = 32, p.date_upd=now() where p.id_product = 572 ;
UPDATE saskitps_product p set p.price = 0.68189, p.date_upd=now() where p.id_product = 577 ;
UPDATE saskitps_product_shop p set p.price = 0.68189, p.date_upd=now() where p.id_product = 577 ;
UPDATE saskitps_product p set p.price = 2603.44, p.date_upd=now() where p.id_product = 578 ;
UPDATE saskitps_product_shop p set p.price = 2603.44, p.date_upd=now() where p.id_product = 578 ;
UPDATE saskitps_product p set p.price = 718.05, p.date_upd=now() where p.id_product = 511 ;
UPDATE saskitps_product_shop p set p.price = 718.05, p.date_upd=now() where p.id_product = 511 ;

UPDATE saskitps_product_attribute pa set pa.price = 0 where pa.id_product = 18 and pa.id_product_attribute = 2495 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 0 where pa.id_product = 18 and pa.id_product_attribute = 2495 ;
UPDATE saskitps_product_attribute pa set pa.price = 70.3 where pa.id_product = 18 and pa.id_product_attribute = 2496 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 70.3 where pa.id_product = 18 and pa.id_product_attribute = 2496 ;
UPDATE saskitps_product_attribute pa set pa.price = 155.98 where pa.id_product = 18 and pa.id_product_attribute = 2497 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 155.98 where pa.id_product = 18 and pa.id_product_attribute = 2497 ;
UPDATE saskitps_product_attribute pa set pa.price = 210.11 where pa.id_product = 18 and pa.id_product_attribute = 2498 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 210.11 where pa.id_product = 18 and pa.id_product_attribute = 2498 ;
UPDATE saskitps_product_attribute pa set pa.price = 314.47 where pa.id_product = 18 and pa.id_product_attribute = 2499 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 314.47 where pa.id_product = 18 and pa.id_product_attribute = 2499 ;
UPDATE saskitps_product_attribute pa set pa.price = 292.76 where pa.id_product = 18 and pa.id_product_attribute = 2500 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 292.76 where pa.id_product = 18 and pa.id_product_attribute = 2500 ;
UPDATE saskitps_product_attribute pa set pa.price = 318.36 where pa.id_product = 18 and pa.id_product_attribute = 2502 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 318.36 where pa.id_product = 18 and pa.id_product_attribute = 2502 ;
UPDATE saskitps_product_attribute pa set pa.price = 471.98 where pa.id_product = 18 and pa.id_product_attribute = 2503 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 471.98 where pa.id_product = 18 and pa.id_product_attribute = 2503 ;
UPDATE saskitps_product_attribute pa set pa.price = 452.81 where pa.id_product = 18 and pa.id_product_attribute = 2504 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 452.81 where pa.id_product = 18 and pa.id_product_attribute = 2504 ;
UPDATE saskitps_product_attribute pa set pa.price = 475.87 where pa.id_product = 18 and pa.id_product_attribute = 2505 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 475.87 where pa.id_product = 18 and pa.id_product_attribute = 2505 ;
UPDATE saskitps_product_attribute pa set pa.price = 580.28 where pa.id_product = 18 and pa.id_product_attribute = 2506 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 580.28 where pa.id_product = 18 and pa.id_product_attribute = 2506 ;
UPDATE saskitps_product_attribute pa set pa.price = 479.75 where pa.id_product = 18 and pa.id_product_attribute = 2507 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 479.75 where pa.id_product = 18 and pa.id_product_attribute = 2507 ;
UPDATE saskitps_product_attribute pa set pa.price = 535.02 where pa.id_product = 18 and pa.id_product_attribute = 2508 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 535.02 where pa.id_product = 18 and pa.id_product_attribute = 2508 ;
UPDATE saskitps_product_attribute pa set pa.price = 626.73 where pa.id_product = 18 and pa.id_product_attribute = 2509 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 626.73 where pa.id_product = 18 and pa.id_product_attribute = 2509 ;
UPDATE saskitps_product_attribute pa set pa.price = 713.25 where pa.id_product = 18 and pa.id_product_attribute = 2510 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 713.25 where pa.id_product = 18 and pa.id_product_attribute = 2510 ;
UPDATE saskitps_product_attribute pa set pa.price = 845.66 where pa.id_product = 18 and pa.id_product_attribute = 2511 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 845.66 where pa.id_product = 18 and pa.id_product_attribute = 2511 ;
UPDATE saskitps_product_attribute pa set pa.price = 721.02 where pa.id_product = 18 and pa.id_product_attribute = 2512 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 721.02 where pa.id_product = 18 and pa.id_product_attribute = 2512 ;
UPDATE saskitps_product_attribute pa set pa.price = 972.09 where pa.id_product = 18 and pa.id_product_attribute = 2513 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 972.09 where pa.id_product = 18 and pa.id_product_attribute = 2513 ;
UPDATE saskitps_product_attribute pa set pa.price = 1131.26 where pa.id_product = 18 and pa.id_product_attribute = 2514 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 1131.26 where pa.id_product = 18 and pa.id_product_attribute = 2514 ;
UPDATE saskitps_product_attribute pa set pa.price = 1166.57 where pa.id_product = 18 and pa.id_product_attribute = 2515 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 1166.57 where pa.id_product = 18 and pa.id_product_attribute = 2515 ;
UPDATE saskitps_product_attribute pa set pa.price = 1286.41 where pa.id_product = 18 and pa.id_product_attribute = 2516 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 1286.41 where pa.id_product = 18 and pa.id_product_attribute = 2516 ;
UPDATE saskitps_product_attribute pa set pa.price = 1291.76 where pa.id_product = 18 and pa.id_product_attribute = 2517 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 1291.76 where pa.id_product = 18 and pa.id_product_attribute = 2517 ;
UPDATE saskitps_product_attribute pa set pa.price = 0.5 where pa.id_product = 27 and pa.id_product_attribute = 447 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 0.5 where pa.id_product = 27 and pa.id_product_attribute = 447 ;
UPDATE saskitps_product_attribute pa set pa.price = 0 where pa.id_product = 29 and pa.id_product_attribute = 372 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 0 where pa.id_product = 29 and pa.id_product_attribute = 372 ;
UPDATE saskitps_product_attribute pa set pa.price = 51.87 where pa.id_product = 29 and pa.id_product_attribute = 373 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 51.87 where pa.id_product = 29 and pa.id_product_attribute = 373 ;
UPDATE saskitps_product_attribute pa set pa.price = 56.69 where pa.id_product = 29 and pa.id_product_attribute = 374 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 56.69 where pa.id_product = 29 and pa.id_product_attribute = 374 ;
UPDATE saskitps_product_attribute pa set pa.price = 108.49 where pa.id_product = 29 and pa.id_product_attribute = 375 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 108.49 where pa.id_product = 29 and pa.id_product_attribute = 375 ;
UPDATE saskitps_product_attribute pa set pa.price = 229.78 where pa.id_product = 29 and pa.id_product_attribute = 376 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 229.78 where pa.id_product = 29 and pa.id_product_attribute = 376 ;
UPDATE saskitps_product_attribute pa set pa.price = 287.84 where pa.id_product = 29 and pa.id_product_attribute = 377 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 287.84 where pa.id_product = 29 and pa.id_product_attribute = 377 ;
UPDATE saskitps_product_attribute pa set pa.price = 351.97 where pa.id_product = 29 and pa.id_product_attribute = 378 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 351.97 where pa.id_product = 29 and pa.id_product_attribute = 378 ;
UPDATE saskitps_product_attribute pa set pa.price = 377.38 where pa.id_product = 29 and pa.id_product_attribute = 379 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 377.38 where pa.id_product = 29 and pa.id_product_attribute = 379 ;
UPDATE saskitps_product_attribute pa set pa.price = 459.4 where pa.id_product = 29 and pa.id_product_attribute = 380 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 459.4 where pa.id_product = 29 and pa.id_product_attribute = 380 ;
UPDATE saskitps_product_attribute pa set pa.price = 577.86 where pa.id_product = 29 and pa.id_product_attribute = 381 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 577.86 where pa.id_product = 29 and pa.id_product_attribute = 381 ;
UPDATE saskitps_product_attribute pa set pa.price = 620.42 where pa.id_product = 29 and pa.id_product_attribute = 382 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 620.42 where pa.id_product = 29 and pa.id_product_attribute = 382 ;
UPDATE saskitps_product_attribute pa set pa.price = 744.6 where pa.id_product = 29 and pa.id_product_attribute = 383 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 744.6 where pa.id_product = 29 and pa.id_product_attribute = 383 ;
UPDATE saskitps_product_attribute pa set pa.price = 996.74 where pa.id_product = 29 and pa.id_product_attribute = 384 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 996.74 where pa.id_product = 29 and pa.id_product_attribute = 384 ;
UPDATE saskitps_product_attribute pa set pa.price = 1041.54 where pa.id_product = 29 and pa.id_product_attribute = 385 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 1041.54 where pa.id_product = 29 and pa.id_product_attribute = 385 ;
UPDATE saskitps_product_attribute pa set pa.price = 0 where pa.id_product = 122 and pa.id_product_attribute = 2456 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 0 where pa.id_product = 122 and pa.id_product_attribute = 2456 ;
UPDATE saskitps_product_attribute pa set pa.price = 0 where pa.id_product = 149 and pa.id_product_attribute = 466 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 0 where pa.id_product = 149 and pa.id_product_attribute = 466 ;
UPDATE saskitps_product_attribute pa set pa.price = 2.98 where pa.id_product = 149 and pa.id_product_attribute = 467 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 2.98 where pa.id_product = 149 and pa.id_product_attribute = 467 ;
UPDATE saskitps_product_attribute pa set pa.price = 0 where pa.id_product = 151 and pa.id_product_attribute = 339 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 0 where pa.id_product = 151 and pa.id_product_attribute = 339 ;
UPDATE saskitps_product_attribute pa set pa.price = 32.52 where pa.id_product = 151 and pa.id_product_attribute = 340 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 32.52 where pa.id_product = 151 and pa.id_product_attribute = 340 ;
UPDATE saskitps_product_attribute pa set pa.price = 95.36 where pa.id_product = 151 and pa.id_product_attribute = 341 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 95.36 where pa.id_product = 151 and pa.id_product_attribute = 341 ;
UPDATE saskitps_product_attribute pa set pa.price = 138.27 where pa.id_product = 151 and pa.id_product_attribute = 342 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 138.27 where pa.id_product = 151 and pa.id_product_attribute = 342 ;
UPDATE saskitps_product_attribute pa set pa.price = 0 where pa.id_product = 153 and pa.id_product_attribute = 417 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 0 where pa.id_product = 153 and pa.id_product_attribute = 417 ;
UPDATE saskitps_product_attribute pa set pa.price = 0.02444 where pa.id_product = 153 and pa.id_product_attribute = 419 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 0.02444 where pa.id_product = 153 and pa.id_product_attribute = 419 ;
UPDATE saskitps_product_attribute pa set pa.price = 0.06116 where pa.id_product = 153 and pa.id_product_attribute = 422 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 0.06116 where pa.id_product = 153 and pa.id_product_attribute = 422 ;
UPDATE saskitps_product_attribute pa set pa.price = 0.09159 where pa.id_product = 153 and pa.id_product_attribute = 425 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 0.09159 where pa.id_product = 153 and pa.id_product_attribute = 425 ;
UPDATE saskitps_product_attribute pa set pa.price = 0.12231 where pa.id_product = 153 and pa.id_product_attribute = 428 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 0.12231 where pa.id_product = 153 and pa.id_product_attribute = 428 ;
UPDATE saskitps_product_attribute pa set pa.price = 0.15874 where pa.id_product = 153 and pa.id_product_attribute = 429 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 0.15874 where pa.id_product = 153 and pa.id_product_attribute = 429 ;
UPDATE saskitps_product_attribute pa set pa.price = 0.18332 where pa.id_product = 153 and pa.id_product_attribute = 430 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 0.18332 where pa.id_product = 153 and pa.id_product_attribute = 430 ;
UPDATE saskitps_product_attribute pa set pa.price = 0.24447 where pa.id_product = 153 and pa.id_product_attribute = 431 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 0.24447 where pa.id_product = 153 and pa.id_product_attribute = 431 ;
UPDATE saskitps_product_attribute pa set pa.price = 0 where pa.id_product = 154 and pa.id_product_attribute = 2367 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 0 where pa.id_product = 154 and pa.id_product_attribute = 2367 ;
UPDATE saskitps_product_attribute pa set pa.price = 218.49 where pa.id_product = 154 and pa.id_product_attribute = 2368 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 218.49 where pa.id_product = 154 and pa.id_product_attribute = 2368 ;
UPDATE saskitps_product_attribute pa set pa.price = 1112.76 where pa.id_product = 154 and pa.id_product_attribute = 2369 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 1112.76 where pa.id_product = 154 and pa.id_product_attribute = 2369 ;
UPDATE saskitps_product_attribute pa set pa.price = 1549.76 where pa.id_product = 154 and pa.id_product_attribute = 2370 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 1549.76 where pa.id_product = 154 and pa.id_product_attribute = 2370 ;
UPDATE saskitps_product_attribute pa set pa.price = 3338.29 where pa.id_product = 154 and pa.id_product_attribute = 2371 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 3338.29 where pa.id_product = 154 and pa.id_product_attribute = 2371 ;
UPDATE saskitps_product_attribute pa set pa.price = 4212.28 where pa.id_product = 154 and pa.id_product_attribute = 2372 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 4212.28 where pa.id_product = 154 and pa.id_product_attribute = 2372 ;
UPDATE saskitps_product_attribute pa set pa.price = 7789.35 where pa.id_product = 154 and pa.id_product_attribute = 2373 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 7789.35 where pa.id_product = 154 and pa.id_product_attribute = 2373 ;
UPDATE saskitps_product_attribute pa set pa.price = 0 where pa.id_product = 158 and pa.id_product_attribute = 2518 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 0 where pa.id_product = 158 and pa.id_product_attribute = 2518 ;
UPDATE saskitps_product_attribute pa set pa.price = 84.58 where pa.id_product = 158 and pa.id_product_attribute = 2519 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 84.58 where pa.id_product = 158 and pa.id_product_attribute = 2519 ;
UPDATE saskitps_product_attribute pa set pa.price = 159.02 where pa.id_product = 158 and pa.id_product_attribute = 2520 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 159.02 where pa.id_product = 158 and pa.id_product_attribute = 2520 ;
UPDATE saskitps_product_attribute pa set pa.price = 315.04 where pa.id_product = 158 and pa.id_product_attribute = 2521 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 315.04 where pa.id_product = 158 and pa.id_product_attribute = 2521 ;
UPDATE saskitps_product_attribute pa set pa.price = 454.34 where pa.id_product = 158 and pa.id_product_attribute = 2522 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 454.34 where pa.id_product = 158 and pa.id_product_attribute = 2522 ;
UPDATE saskitps_product_attribute pa set pa.price = 389.49 where pa.id_product = 158 and pa.id_product_attribute = 2523 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 389.49 where pa.id_product = 158 and pa.id_product_attribute = 2523 ;
UPDATE saskitps_product_attribute pa set pa.price = 545.51 where pa.id_product = 158 and pa.id_product_attribute = 2524 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 545.51 where pa.id_product = 158 and pa.id_product_attribute = 2524 ;
UPDATE saskitps_product_attribute pa set pa.price = 619.96 where pa.id_product = 158 and pa.id_product_attribute = 2525 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 619.96 where pa.id_product = 158 and pa.id_product_attribute = 2525 ;
UPDATE saskitps_product_attribute pa set pa.price = 775.98 where pa.id_product = 158 and pa.id_product_attribute = 2526 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 775.98 where pa.id_product = 158 and pa.id_product_attribute = 2526 ;
UPDATE saskitps_product_attribute pa set pa.price = 1075.73 where pa.id_product = 158 and pa.id_product_attribute = 2527 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 1075.73 where pa.id_product = 158 and pa.id_product_attribute = 2527 ;
UPDATE saskitps_product_attribute pa set pa.price = 1272.05 where pa.id_product = 158 and pa.id_product_attribute = 2528 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 1272.05 where pa.id_product = 158 and pa.id_product_attribute = 2528 ;
UPDATE saskitps_product_attribute pa set pa.price = 1168.27 where pa.id_product = 158 and pa.id_product_attribute = 2529 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 1168.27 where pa.id_product = 158 and pa.id_product_attribute = 2529 ;
UPDATE saskitps_product_attribute pa set pa.price = 1521.08 where pa.id_product = 158 and pa.id_product_attribute = 2530 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 1521.08 where pa.id_product = 158 and pa.id_product_attribute = 2530 ;
UPDATE saskitps_product_attribute pa set pa.price = 1669.97 where pa.id_product = 158 and pa.id_product_attribute = 2531 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 1669.97 where pa.id_product = 158 and pa.id_product_attribute = 2531 ;
UPDATE saskitps_product_attribute pa set pa.price = 1837.65 where pa.id_product = 158 and pa.id_product_attribute = 2532 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 1837.65 where pa.id_product = 158 and pa.id_product_attribute = 2532 ;
UPDATE saskitps_product_attribute pa set pa.price = 726.81 where pa.id_product = 158 and pa.id_product_attribute = 2533 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 726.81 where pa.id_product = 158 and pa.id_product_attribute = 2533 ;
UPDATE saskitps_product_attribute pa set pa.price = 625.81 where pa.id_product = 158 and pa.id_product_attribute = 2534 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 625.81 where pa.id_product = 158 and pa.id_product_attribute = 2534 ;
UPDATE saskitps_product_attribute pa set pa.price = 1019.38 where pa.id_product = 158 and pa.id_product_attribute = 2535 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 1019.38 where pa.id_product = 158 and pa.id_product_attribute = 2535 ;
UPDATE saskitps_product_attribute pa set pa.price = 1727.9 where pa.id_product = 158 and pa.id_product_attribute = 2536 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 1727.9 where pa.id_product = 158 and pa.id_product_attribute = 2536 ;
UPDATE saskitps_product_attribute pa set pa.price = 1791.47 where pa.id_product = 158 and pa.id_product_attribute = 2537 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 1791.47 where pa.id_product = 158 and pa.id_product_attribute = 2537 ;
UPDATE saskitps_product_attribute pa set pa.price = 0 where pa.id_product = 440 and pa.id_product_attribute = 450 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 0 where pa.id_product = 440 and pa.id_product_attribute = 450 ;
UPDATE saskitps_product_attribute pa set pa.price = 0.494 where pa.id_product = 440 and pa.id_product_attribute = 451 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 0.494 where pa.id_product = 440 and pa.id_product_attribute = 451 ;
UPDATE saskitps_product_attribute pa set pa.price = 0 where pa.id_product = 441 and pa.id_product_attribute = 453 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 0 where pa.id_product = 441 and pa.id_product_attribute = 453 ;
UPDATE saskitps_product_attribute pa set pa.price = 0.429 where pa.id_product = 441 and pa.id_product_attribute = 454 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 0.429 where pa.id_product = 441 and pa.id_product_attribute = 454 ;
UPDATE saskitps_product_attribute pa set pa.price = 0 where pa.id_product = 442 and pa.id_product_attribute = 456 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 0 where pa.id_product = 442 and pa.id_product_attribute = 456 ;
UPDATE saskitps_product_attribute pa set pa.price = 0.40781 where pa.id_product = 442 and pa.id_product_attribute = 457 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 0.40781 where pa.id_product = 442 and pa.id_product_attribute = 457 ;
UPDATE saskitps_product_attribute pa set pa.price = 0 where pa.id_product = 465 and pa.id_product_attribute = 534 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 0 where pa.id_product = 465 and pa.id_product_attribute = 534 ;
UPDATE saskitps_product_attribute pa set pa.price = 2.96 where pa.id_product = 465 and pa.id_product_attribute = 535 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 2.96 where pa.id_product = 465 and pa.id_product_attribute = 535 ;
UPDATE saskitps_product_attribute pa set pa.price = 0 where pa.id_product = 511 and pa.id_product_attribute = 2475 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 0 where pa.id_product = 511 and pa.id_product_attribute = 2475 ;
UPDATE saskitps_product_attribute pa set pa.price = 170.26 where pa.id_product = 511 and pa.id_product_attribute = 2476 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 170.26 where pa.id_product = 511 and pa.id_product_attribute = 2476 ;
UPDATE saskitps_product_attribute pa set pa.price = 298.83 where pa.id_product = 511 and pa.id_product_attribute = 2477 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 298.83 where pa.id_product = 511 and pa.id_product_attribute = 2477 ;
UPDATE saskitps_product_attribute pa set pa.price = 559.22 where pa.id_product = 511 and pa.id_product_attribute = 2478 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 559.22 where pa.id_product = 511 and pa.id_product_attribute = 2478 ;
UPDATE saskitps_product_attribute pa set pa.price = 676.8 where pa.id_product = 511 and pa.id_product_attribute = 2479 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 676.8 where pa.id_product = 511 and pa.id_product_attribute = 2479 ;
UPDATE saskitps_product_attribute pa set pa.price = 637.55 where pa.id_product = 511 and pa.id_product_attribute = 2480 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 637.55 where pa.id_product = 511 and pa.id_product_attribute = 2480 ;
UPDATE saskitps_product_attribute pa set pa.price = 947.19 where pa.id_product = 511 and pa.id_product_attribute = 2481 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 947.19 where pa.id_product = 511 and pa.id_product_attribute = 2481 ;
UPDATE saskitps_product_attribute pa set pa.price = 1109.32 where pa.id_product = 511 and pa.id_product_attribute = 2482 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 1109.32 where pa.id_product = 511 and pa.id_product_attribute = 2482 ;
UPDATE saskitps_product_attribute pa set pa.price = 1025.53 where pa.id_product = 511 and pa.id_product_attribute = 2483 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 1025.53 where pa.id_product = 511 and pa.id_product_attribute = 2483 ;
UPDATE saskitps_product_attribute pa set pa.price = 1185.43 where pa.id_product = 511 and pa.id_product_attribute = 2484 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 1185.43 where pa.id_product = 511 and pa.id_product_attribute = 2484 ;
UPDATE saskitps_product_attribute pa set pa.price = 1593.48 where pa.id_product = 511 and pa.id_product_attribute = 2485 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 1593.48 where pa.id_product = 511 and pa.id_product_attribute = 2485 ;
UPDATE saskitps_product_attribute pa set pa.price = 2047.41 where pa.id_product = 511 and pa.id_product_attribute = 2486 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 2047.41 where pa.id_product = 511 and pa.id_product_attribute = 2486 ;
UPDATE saskitps_product_attribute pa set pa.price = 2422.86 where pa.id_product = 511 and pa.id_product_attribute = 2487 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 2422.86 where pa.id_product = 511 and pa.id_product_attribute = 2487 ;
UPDATE saskitps_product_attribute pa set pa.price = 2579.53 where pa.id_product = 511 and pa.id_product_attribute = 2488 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 2579.53 where pa.id_product = 511 and pa.id_product_attribute = 2488 ;
UPDATE saskitps_product_attribute pa set pa.price = 2724.41 where pa.id_product = 511 and pa.id_product_attribute = 2489 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 2724.41 where pa.id_product = 511 and pa.id_product_attribute = 2489 ;
UPDATE saskitps_product_attribute pa set pa.price = 1090.53 where pa.id_product = 511 and pa.id_product_attribute = 2490 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 1090.53 where pa.id_product = 511 and pa.id_product_attribute = 2490 ;
UPDATE saskitps_product_attribute pa set pa.price = 1662.32 where pa.id_product = 511 and pa.id_product_attribute = 2491 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 1662.32 where pa.id_product = 511 and pa.id_product_attribute = 2491 ;
UPDATE saskitps_product_attribute pa set pa.price = 1819 where pa.id_product = 511 and pa.id_product_attribute = 2492 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 1819 where pa.id_product = 511 and pa.id_product_attribute = 2492 ;
UPDATE saskitps_product_attribute pa set pa.price = 2619.62 where pa.id_product = 511 and pa.id_product_attribute = 2493 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 2619.62 where pa.id_product = 511 and pa.id_product_attribute = 2493 ;
UPDATE saskitps_product_attribute pa set pa.price = 2908.38 where pa.id_product = 511 and pa.id_product_attribute = 2494 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 2908.38 where pa.id_product = 511 and pa.id_product_attribute = 2494 ;
UPDATE saskitps_product_attribute pa set pa.price = 2.24 where pa.id_product = 526 and pa.id_product_attribute = 724 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 2.24 where pa.id_product = 526 and pa.id_product_attribute = 724 ;
UPDATE saskitps_product_attribute pa set pa.price = 0 where pa.id_product = 526 and pa.id_product_attribute = 725 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 0 where pa.id_product = 526 and pa.id_product_attribute = 725 ;
UPDATE saskitps_product_attribute pa set pa.price = 0 where pa.id_product = 532 and pa.id_product_attribute = 896 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 0 where pa.id_product = 532 and pa.id_product_attribute = 896 ;
UPDATE saskitps_product_attribute pa set pa.price = 84.3 where pa.id_product = 532 and pa.id_product_attribute = 897 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 84.3 where pa.id_product = 532 and pa.id_product_attribute = 897 ;
UPDATE saskitps_product_attribute pa set pa.price = 3.90 where pa.id_product = 532 and pa.id_product_attribute = 898 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 3.90 where pa.id_product = 532 and pa.id_product_attribute = 898 ;
UPDATE saskitps_product_attribute pa set pa.price = 112.4 where pa.id_product = 532 and pa.id_product_attribute = 899 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 112.4 where pa.id_product = 532 and pa.id_product_attribute = 899 ;
UPDATE saskitps_product_attribute pa set pa.price = 54.42 where pa.id_product = 532 and pa.id_product_attribute = 900 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 54.42 where pa.id_product = 532 and pa.id_product_attribute = 900 ;
UPDATE saskitps_product_attribute pa set pa.price = 158.29 where pa.id_product = 532 and pa.id_product_attribute = 901 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 158.29 where pa.id_product = 532 and pa.id_product_attribute = 901 ;
UPDATE saskitps_product_attribute pa set pa.price = 81 where pa.id_product = 532 and pa.id_product_attribute = 906 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 81 where pa.id_product = 532 and pa.id_product_attribute = 906 ;
UPDATE saskitps_product_attribute pa set pa.price = 193.22 where pa.id_product = 532 and pa.id_product_attribute = 907 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 193.22 where pa.id_product = 532 and pa.id_product_attribute = 907 ;
UPDATE saskitps_product_attribute pa set pa.price = 78.85 where pa.id_product = 532 and pa.id_product_attribute = 908 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 78.85 where pa.id_product = 532 and pa.id_product_attribute = 908 ;
UPDATE saskitps_product_attribute pa set pa.price = 210.47 where pa.id_product = 532 and pa.id_product_attribute = 909 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 210.47 where pa.id_product = 532 and pa.id_product_attribute = 909 ;
UPDATE saskitps_product_attribute pa set pa.price = 154.28 where pa.id_product = 532 and pa.id_product_attribute = 910 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 154.28 where pa.id_product = 532 and pa.id_product_attribute = 910 ;
UPDATE saskitps_product_attribute pa set pa.price = 258.96 where pa.id_product = 532 and pa.id_product_attribute = 911 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 258.96 where pa.id_product = 532 and pa.id_product_attribute = 911 ;
UPDATE saskitps_product_attribute pa set pa.price = 94.08 where pa.id_product = 532 and pa.id_product_attribute = 916 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 94.08 where pa.id_product = 532 and pa.id_product_attribute = 916 ;
UPDATE saskitps_product_attribute pa set pa.price = 198.8 where pa.id_product = 532 and pa.id_product_attribute = 917 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 198.8 where pa.id_product = 532 and pa.id_product_attribute = 917 ;
UPDATE saskitps_product_attribute pa set pa.price = 109.33 where pa.id_product = 532 and pa.id_product_attribute = 918 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 109.33 where pa.id_product = 532 and pa.id_product_attribute = 918 ;
UPDATE saskitps_product_attribute pa set pa.price = 221.32 where pa.id_product = 532 and pa.id_product_attribute = 919 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 221.32 where pa.id_product = 532 and pa.id_product_attribute = 919 ;
UPDATE saskitps_product_attribute pa set pa.price = 164.36 where pa.id_product = 532 and pa.id_product_attribute = 920 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 164.36 where pa.id_product = 532 and pa.id_product_attribute = 920 ;
UPDATE saskitps_product_attribute pa set pa.price = 260.15 where pa.id_product = 532 and pa.id_product_attribute = 921 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 260.15 where pa.id_product = 532 and pa.id_product_attribute = 921 ;
UPDATE saskitps_product_attribute pa set pa.price = 363.91 where pa.id_product = 532 and pa.id_product_attribute = 937 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 363.91 where pa.id_product = 532 and pa.id_product_attribute = 937 ;
UPDATE saskitps_product_attribute pa set pa.price = 463.16 where pa.id_product = 532 and pa.id_product_attribute = 939 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 463.16 where pa.id_product = 532 and pa.id_product_attribute = 939 ;
UPDATE saskitps_product_attribute pa set pa.price = 458.42 where pa.id_product = 532 and pa.id_product_attribute = 941 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 458.42 where pa.id_product = 532 and pa.id_product_attribute = 941 ;

UPDATE saskitps_product_attribute pa set pa.price = 5.08 where pa.id_product = 536 and pa.id_product_attribute = 934 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 5.08 where pa.id_product = 536 and pa.id_product_attribute = 934 ;
UPDATE saskitps_product_attribute pa set pa.price = 0 where pa.id_product = 558 and pa.id_product_attribute = 2335 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 0 where pa.id_product = 558 and pa.id_product_attribute = 2335 ;
UPDATE saskitps_product_attribute pa set pa.price = 1.31000000000006 where pa.id_product = 558 and pa.id_product_attribute = 2336 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 1.31000000000006 where pa.id_product = 558 and pa.id_product_attribute = 2336 ;
UPDATE saskitps_product_attribute pa set pa.price = 226.11 where pa.id_product = 558 and pa.id_product_attribute = 2337 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 226.11 where pa.id_product = 558 and pa.id_product_attribute = 2337 ;
UPDATE saskitps_product_attribute pa set pa.price = 364.49 where pa.id_product = 558 and pa.id_product_attribute = 2338 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 364.49 where pa.id_product = 558 and pa.id_product_attribute = 2338 ;
UPDATE saskitps_product_attribute pa set pa.price = 478.51 where pa.id_product = 558 and pa.id_product_attribute = 2339 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 478.51 where pa.id_product = 558 and pa.id_product_attribute = 2339 ;
UPDATE saskitps_product_attribute pa set pa.price = 509.28 where pa.id_product = 558 and pa.id_product_attribute = 2340 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 509.28 where pa.id_product = 558 and pa.id_product_attribute = 2340 ;
UPDATE saskitps_product_attribute pa set pa.price = 594.33 where pa.id_product = 558 and pa.id_product_attribute = 2341 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 594.33 where pa.id_product = 558 and pa.id_product_attribute = 2341 ;
UPDATE saskitps_product_attribute pa set pa.price = 659.19 where pa.id_product = 558 and pa.id_product_attribute = 2342 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 659.19 where pa.id_product = 558 and pa.id_product_attribute = 2342 ;
UPDATE saskitps_product_attribute pa set pa.price = 806.84 where pa.id_product = 558 and pa.id_product_attribute = 2343 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 806.84 where pa.id_product = 558 and pa.id_product_attribute = 2343 ;
UPDATE saskitps_product_attribute pa set pa.price = 1012.25 where pa.id_product = 558 and pa.id_product_attribute = 2344 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 1012.25 where pa.id_product = 558 and pa.id_product_attribute = 2344 ;
UPDATE saskitps_product_attribute pa set pa.price = 1147.86 where pa.id_product = 558 and pa.id_product_attribute = 2345 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 1147.86 where pa.id_product = 558 and pa.id_product_attribute = 2345 ;
UPDATE saskitps_product_attribute pa set pa.price = 1274.31 where pa.id_product = 558 and pa.id_product_attribute = 2346 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 1274.31 where pa.id_product = 558 and pa.id_product_attribute = 2346 ;
UPDATE saskitps_product_attribute pa set pa.price = 1148.01 where pa.id_product = 558 and pa.id_product_attribute = 2347 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 1148.01 where pa.id_product = 558 and pa.id_product_attribute = 2347 ;
UPDATE saskitps_product_attribute pa set pa.price = 1559.36 where pa.id_product = 558 and pa.id_product_attribute = 2348 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 1559.36 where pa.id_product = 558 and pa.id_product_attribute = 2348 ;
UPDATE saskitps_product_attribute pa set pa.price = 1648.24 where pa.id_product = 558 and pa.id_product_attribute = 2349 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 1648.24 where pa.id_product = 558 and pa.id_product_attribute = 2349 ;
UPDATE saskitps_product_attribute pa set pa.price = 1763.39 where pa.id_product = 558 and pa.id_product_attribute = 2350 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 1763.39 where pa.id_product = 558 and pa.id_product_attribute = 2350 ;
UPDATE saskitps_product_attribute pa set pa.price = 0.13232 where pa.id_product = 560 and pa.id_product_attribute = 1514 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 0.13232 where pa.id_product = 560 and pa.id_product_attribute = 1514 ;
UPDATE saskitps_product_attribute pa set pa.price = 0.41643 where pa.id_product = 560 and pa.id_product_attribute = 1516 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 0.41643 where pa.id_product = 560 and pa.id_product_attribute = 1516 ;
UPDATE saskitps_product_attribute pa set pa.price = 0.70054 where pa.id_product = 560 and pa.id_product_attribute = 1517 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 0.70054 where pa.id_product = 560 and pa.id_product_attribute = 1517 ;
UPDATE saskitps_product_attribute pa set pa.price = 0 where pa.id_product = 560 and pa.id_product_attribute = 2553 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 0 where pa.id_product = 560 and pa.id_product_attribute = 2553 ;
UPDATE saskitps_product_attribute pa set pa.price = 0 where pa.id_product = 562 and pa.id_product_attribute = 1550 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 0 where pa.id_product = 562 and pa.id_product_attribute = 1550 ;
UPDATE saskitps_product_attribute pa set pa.price = 0 where pa.id_product = 562 and pa.id_product_attribute = 1551 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 0 where pa.id_product = 562 and pa.id_product_attribute = 1551 ;
UPDATE saskitps_product_attribute pa set pa.price = 4.69 where pa.id_product = 562 and pa.id_product_attribute = 1552 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 4.69 where pa.id_product = 562 and pa.id_product_attribute = 1552 ;
UPDATE saskitps_product_attribute pa set pa.price = 17.85 where pa.id_product = 562 and pa.id_product_attribute = 1553 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 17.85 where pa.id_product = 562 and pa.id_product_attribute = 1553 ;
UPDATE saskitps_product_attribute pa set pa.price = 4.41 where pa.id_product = 562 and pa.id_product_attribute = 1554 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 4.41 where pa.id_product = 562 and pa.id_product_attribute = 1554 ;
UPDATE saskitps_product_attribute pa set pa.price = 27.76 where pa.id_product = 562 and pa.id_product_attribute = 1555 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 27.76 where pa.id_product = 562 and pa.id_product_attribute = 1555 ;
UPDATE saskitps_product_attribute pa set pa.price = 37 where pa.id_product = 562 and pa.id_product_attribute = 1556 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 37 where pa.id_product = 562 and pa.id_product_attribute = 1556 ;
UPDATE saskitps_product_attribute pa set pa.price = 38.69 where pa.id_product = 562 and pa.id_product_attribute = 1557 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 38.69 where pa.id_product = 562 and pa.id_product_attribute = 1557 ;
UPDATE saskitps_product_attribute pa set pa.price = 53.8 where pa.id_product = 562 and pa.id_product_attribute = 1558 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 53.8 where pa.id_product = 562 and pa.id_product_attribute = 1558 ;
UPDATE saskitps_product_attribute pa set pa.price = 66.67 where pa.id_product = 562 and pa.id_product_attribute = 1559 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 66.67 where pa.id_product = 562 and pa.id_product_attribute = 1559 ;
UPDATE saskitps_product_attribute pa set pa.price = 17.85 where pa.id_product = 562 and pa.id_product_attribute = 1560 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 17.85 where pa.id_product = 562 and pa.id_product_attribute = 1560 ;
UPDATE saskitps_product_attribute pa set pa.price = 60.18 where pa.id_product = 562 and pa.id_product_attribute = 1561 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 60.18 where pa.id_product = 562 and pa.id_product_attribute = 1561 ;
UPDATE saskitps_product_attribute pa set pa.price = 67.17 where pa.id_product = 562 and pa.id_product_attribute = 1562 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 67.17 where pa.id_product = 562 and pa.id_product_attribute = 1562 ;
UPDATE saskitps_product_attribute pa set pa.price = 67.17 where pa.id_product = 562 and pa.id_product_attribute = 1563 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 67.17 where pa.id_product = 562 and pa.id_product_attribute = 1563 ;
UPDATE saskitps_product_attribute pa set pa.price = 72.61 where pa.id_product = 562 and pa.id_product_attribute = 1564 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 72.61 where pa.id_product = 562 and pa.id_product_attribute = 1564 ;
UPDATE saskitps_product_attribute pa set pa.price = 83.1 where pa.id_product = 562 and pa.id_product_attribute = 1565 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 83.1 where pa.id_product = 562 and pa.id_product_attribute = 1565 ;
UPDATE saskitps_product_attribute pa set pa.price = 0 where pa.id_product = 563 and pa.id_product_attribute = 2351 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 0 where pa.id_product = 563 and pa.id_product_attribute = 2351 ;
UPDATE saskitps_product_attribute pa set pa.price = 197.64 where pa.id_product = 563 and pa.id_product_attribute = 2352 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 197.64 where pa.id_product = 563 and pa.id_product_attribute = 2352 ;
UPDATE saskitps_product_attribute pa set pa.price = 265.03 where pa.id_product = 563 and pa.id_product_attribute = 2353 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 265.03 where pa.id_product = 563 and pa.id_product_attribute = 2353 ;
UPDATE saskitps_product_attribute pa set pa.price = 425.56 where pa.id_product = 563 and pa.id_product_attribute = 2354 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 425.56 where pa.id_product = 563 and pa.id_product_attribute = 2354 ;
UPDATE saskitps_product_attribute pa set pa.price = 522.77 where pa.id_product = 563 and pa.id_product_attribute = 2355 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 522.77 where pa.id_product = 563 and pa.id_product_attribute = 2355 ;
UPDATE saskitps_product_attribute pa set pa.price = 560.6 where pa.id_product = 563 and pa.id_product_attribute = 2356 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 560.6 where pa.id_product = 563 and pa.id_product_attribute = 2356 ;
UPDATE saskitps_product_attribute pa set pa.price = 633.04 where pa.id_product = 563 and pa.id_product_attribute = 2357 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 633.04 where pa.id_product = 563 and pa.id_product_attribute = 2357 ;
UPDATE saskitps_product_attribute pa set pa.price = 697.36 where pa.id_product = 563 and pa.id_product_attribute = 2358 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 697.36 where pa.id_product = 563 and pa.id_product_attribute = 2358 ;
UPDATE saskitps_product_attribute pa set pa.price = 835.5 where pa.id_product = 563 and pa.id_product_attribute = 2359 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 835.5 where pa.id_product = 563 and pa.id_product_attribute = 2359 ;
UPDATE saskitps_product_attribute pa set pa.price = 1049.88 where pa.id_product = 563 and pa.id_product_attribute = 2360 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 1049.88 where pa.id_product = 563 and pa.id_product_attribute = 2360 ;
UPDATE saskitps_product_attribute pa set pa.price = 1208.02 where pa.id_product = 563 and pa.id_product_attribute = 2361 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 1208.02 where pa.id_product = 563 and pa.id_product_attribute = 2361 ;
UPDATE saskitps_product_attribute pa set pa.price = 1319.6 where pa.id_product = 563 and pa.id_product_attribute = 2362 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 1319.6 where pa.id_product = 563 and pa.id_product_attribute = 2362 ;
UPDATE saskitps_product_attribute pa set pa.price = 1176.96 where pa.id_product = 563 and pa.id_product_attribute = 2363 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 1176.96 where pa.id_product = 563 and pa.id_product_attribute = 2363 ;
UPDATE saskitps_product_attribute pa set pa.price = 1601.01 where pa.id_product = 563 and pa.id_product_attribute = 2364 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 1601.01 where pa.id_product = 563 and pa.id_product_attribute = 2364 ;
UPDATE saskitps_product_attribute pa set pa.price = 1679.37 where pa.id_product = 563 and pa.id_product_attribute = 2365 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 1679.37 where pa.id_product = 563 and pa.id_product_attribute = 2365 ;
UPDATE saskitps_product_attribute pa set pa.price = 1777.93 where pa.id_product = 563 and pa.id_product_attribute = 2366 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 1777.93 where pa.id_product = 563 and pa.id_product_attribute = 2366 ;
UPDATE saskitps_product_attribute pa set pa.price = 30.5 where pa.id_product = 572 and pa.id_product_attribute = 2446 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 30.5 where pa.id_product = 572 and pa.id_product_attribute = 2446 ;
UPDATE saskitps_product_attribute pa set pa.price = 88 where pa.id_product = 572 and pa.id_product_attribute = 2447 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 88 where pa.id_product = 572 and pa.id_product_attribute = 2447 ;
UPDATE saskitps_product_attribute pa set pa.price = 0 where pa.id_product = 572 and pa.id_product_attribute = 2449 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 0 where pa.id_product = 572 and pa.id_product_attribute = 2449 ;
UPDATE saskitps_product_attribute pa set pa.price = 0.11265 where pa.id_product = 577 and pa.id_product_attribute = 2538 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 0.11265 where pa.id_product = 577 and pa.id_product_attribute = 2538 ;
UPDATE saskitps_product_attribute pa set pa.price = 0.05589 where pa.id_product = 577 and pa.id_product_attribute = 2539 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 0.05589 where pa.id_product = 577 and pa.id_product_attribute = 2539 ;
UPDATE saskitps_product_attribute pa set pa.price = 0.02795 where pa.id_product = 577 and pa.id_product_attribute = 2540 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 0.02795 where pa.id_product = 577 and pa.id_product_attribute = 2540 ;
UPDATE saskitps_product_attribute pa set pa.price = 0 where pa.id_product = 577 and pa.id_product_attribute = 2554 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 0 where pa.id_product = 577 and pa.id_product_attribute = 2554 ;
UPDATE saskitps_product_attribute pa set pa.price = 0 where pa.id_product = 578 and pa.id_product_attribute = 2561 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 0 where pa.id_product = 578 and pa.id_product_attribute = 2561 ;
UPDATE saskitps_product_attribute pa set pa.price = 613.31 where pa.id_product = 578 and pa.id_product_attribute = 2562 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 613.31 where pa.id_product = 578 and pa.id_product_attribute = 2562 ;
UPDATE saskitps_product_attribute pa set pa.price = 867.81 where pa.id_product = 578 and pa.id_product_attribute = 2563 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 867.81 where pa.id_product = 578 and pa.id_product_attribute = 2563 ;
UPDATE saskitps_product_attribute pa set pa.price = 1685.55 where pa.id_product = 578 and pa.id_product_attribute = 2564 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 1685.55 where pa.id_product = 578 and pa.id_product_attribute = 2564 ;
UPDATE saskitps_product_attribute pa set pa.price = 1735.61 where pa.id_product = 578 and pa.id_product_attribute = 2565 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 1735.61 where pa.id_product = 578 and pa.id_product_attribute = 2565 ;
UPDATE saskitps_product_attribute pa set pa.price = 2757.8 where pa.id_product = 578 and pa.id_product_attribute = 2566 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 2757.8 where pa.id_product = 578 and pa.id_product_attribute = 2566 ;
UPDATE saskitps_product_attribute pa set pa.price = 2603.43 where pa.id_product = 578 and pa.id_product_attribute = 2567 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 2603.43 where pa.id_product = 578 and pa.id_product_attribute = 2567 ;
UPDATE saskitps_product_attribute pa set pa.price = 3830.05 where pa.id_product = 578 and pa.id_product_attribute = 2568 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 3830.05 where pa.id_product = 578 and pa.id_product_attribute = 2568 ;
UPDATE saskitps_product_attribute pa set pa.price = 4339.05 where pa.id_product = 578 and pa.id_product_attribute = 2569 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 4339.05 where pa.id_product = 578 and pa.id_product_attribute = 2569 ;
UPDATE saskitps_product_attribute pa set pa.price = 5974.55 where pa.id_product = 578 and pa.id_product_attribute = 2570 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 5974.55 where pa.id_product = 578 and pa.id_product_attribute = 2570 ;
UPDATE saskitps_product_attribute pa set pa.price = 6074.68 where pa.id_product = 578 and pa.id_product_attribute = 2571 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 6074.68 where pa.id_product = 578 and pa.id_product_attribute = 2571 ;
UPDATE saskitps_product_attribute pa set pa.price = 8119.05 where pa.id_product = 578 and pa.id_product_attribute = 2572 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 8119.05 where pa.id_product = 578 and pa.id_product_attribute = 2572 ;
UPDATE saskitps_product_attribute pa set pa.price = -1.49 where pa.id_product = 588 and pa.id_product_attribute = 2581 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = -1.49 where pa.id_product = 588 and pa.id_product_attribute = 2581 ;
