UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 49, sas.DateModification = NOW() where sas.RefPrestashop = 12 ;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 21.32, sas.DateModification = NOW() where sas.RefPrestashop = 14 ;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 4.26, sas.DateModification = NOW() where sas.RefPrestashop = 58 ;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 4.73, sas.DateModification = NOW() where sas.RefPrestashop = 59 ;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 24.83, sas.DateModification = NOW() where sas.RefPrestashop = 62 ;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 98.54, sas.DateModification = NOW() where sas.RefPrestashop = 99 ;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 114.74, sas.DateModification = NOW() where sas.RefPrestashop = 100 ;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 90.89, sas.DateModification = NOW() where sas.RefPrestashop = 103 ;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 35.66, sas.DateModification = NOW() where sas.RefPrestashop = 104 ;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 200.71, sas.DateModification = NOW() where sas.RefPrestashop = 113 ;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 185.05, sas.DateModification = NOW() where sas.RefPrestashop = 114 ;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 53.8, sas.DateModification = NOW() where sas.RefPrestashop = 118 ;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 200.61, sas.DateModification = NOW() where sas.RefPrestashop = 120 ;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 759.15, sas.DateModification = NOW() where sas.RefPrestashop = 121 ;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 136.32, sas.DateModification = NOW() where sas.RefPrestashop = 123 ;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 187.76, sas.DateModification = NOW() where sas.RefPrestashop = 124 ;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 6.37, sas.DateModification = NOW() where sas.RefPrestashop = 131 ;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 56.7, sas.DateModification = NOW() where sas.RefPrestashop = 137 ;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 639.08, sas.DateModification = NOW() where sas.RefPrestashop = 138 ;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 681.45, sas.DateModification = NOW() where sas.RefPrestashop = 139 ;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 20.78, sas.DateModification = NOW() where sas.RefPrestashop = 188 ;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 16.73, sas.DateModification = NOW() where sas.RefPrestashop = 189 ;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 13.28, sas.DateModification = NOW() where sas.RefPrestashop = 190 ;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 25.04, sas.DateModification = NOW() where sas.RefPrestashop = 193 ;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 16.66, sas.DateModification = NOW() where sas.RefPrestashop = 194 ;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 11.57, sas.DateModification = NOW() where sas.RefPrestashop = 447 ;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 120.54, sas.DateModification = NOW() where sas.RefPrestashop = 450 ;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 1.2688, sas.DateModification = NOW() where sas.RefPrestashop = 453 ;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 526.41, sas.DateModification = NOW() where sas.RefPrestashop = 459 ;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 2.57, sas.DateModification = NOW() where sas.RefPrestashop = 466 ;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 2.01, sas.DateModification = NOW() where sas.RefPrestashop = 467 ;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 3.13, sas.DateModification = NOW() where sas.RefPrestashop = 468 ;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 2.75, sas.DateModification = NOW() where sas.RefPrestashop = 469 ;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 8.54, sas.DateModification = NOW() where sas.RefPrestashop = 470 ;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 27.15, sas.DateModification = NOW() where sas.RefPrestashop = 508 ;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 2.4, sas.DateModification = NOW() where sas.RefPrestashop = 512 ;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 2.06, sas.DateModification = NOW() where sas.RefPrestashop = 513 ;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 11.22, sas.DateModification = NOW() where sas.RefPrestashop = 518 ;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 11.21, sas.DateModification = NOW() where sas.RefPrestashop = 519 ;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 1.4338, sas.DateModification = NOW() where sas.RefPrestashop = 520 ;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 8.05, sas.DateModification = NOW() where sas.RefPrestashop = 521 ;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 3.69, sas.DateModification = NOW() where sas.RefPrestashop = 522 ;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 3.23, sas.DateModification = NOW() where sas.RefPrestashop = 523 ;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 1.31175, sas.DateModification = NOW() where sas.RefPrestashop = 527 ;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 20.63, sas.DateModification = NOW() where sas.RefPrestashop = 528 ;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 7.16, sas.DateModification = NOW() where sas.RefPrestashop = 530 ;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 76.63, sas.DateModification = NOW() where sas.RefPrestashop = 533 ;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 97.58, sas.DateModification = NOW() where sas.RefPrestashop = 534 ;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 2.33, sas.DateModification = NOW() where sas.RefPrestashop = 535 ;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 31.74, sas.DateModification = NOW() where sas.RefPrestashop = 537 ;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 20.81, sas.DateModification = NOW() where sas.RefPrestashop = 540 ;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 21.96, sas.DateModification = NOW() where sas.RefPrestashop = 541 ;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 27.41, sas.DateModification = NOW() where sas.RefPrestashop = 542 ;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 530.42, sas.DateModification = NOW() where sas.RefPrestashop = 546 ;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 160.2, sas.DateModification = NOW() where sas.RefPrestashop = 548 ;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 6.26, sas.DateModification = NOW() where sas.RefPrestashop = 549 ;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 923.65, sas.DateModification = NOW() where sas.RefPrestashop = 554 ;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 36.31, sas.DateModification = NOW() where sas.RefPrestashop = 561 ;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 234.81, sas.DateModification = NOW() where sas.RefPrestashop = 573 ;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 16.76, sas.DateModification = NOW() where sas.RefPrestashop = 581 ;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 86.35, sas.DateModification = NOW() where sas.RefPrestashop = 587 ;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 0.12285, sas.DateModification = NOW() where sas.RefPrestashop = 593 ;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 0.38016, sas.DateModification = NOW() where sas.RefPrestashop = 594 ;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 554.02, sas.DateModification = NOW() where sas.RefPrestashop = 597 ;

UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 339.99, sas.DateModification = NOW() where sas.RefPrestashop = 18 and sas.id_product_attribute = 2495;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 410.29, sas.DateModification = NOW() where sas.RefPrestashop = 18 and sas.id_product_attribute = 2496;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 495.97, sas.DateModification = NOW() where sas.RefPrestashop = 18 and sas.id_product_attribute = 2497;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 550.1, sas.DateModification = NOW() where sas.RefPrestashop = 18 and sas.id_product_attribute = 2498;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 654.46, sas.DateModification = NOW() where sas.RefPrestashop = 18 and sas.id_product_attribute = 2499;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 632.75, sas.DateModification = NOW() where sas.RefPrestashop = 18 and sas.id_product_attribute = 2500;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 658.35, sas.DateModification = NOW() where sas.RefPrestashop = 18 and sas.id_product_attribute = 2502;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 811.97, sas.DateModification = NOW() where sas.RefPrestashop = 18 and sas.id_product_attribute = 2503;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 792.8, sas.DateModification = NOW() where sas.RefPrestashop = 18 and sas.id_product_attribute = 2504;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 815.86, sas.DateModification = NOW() where sas.RefPrestashop = 18 and sas.id_product_attribute = 2505;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 920.27, sas.DateModification = NOW() where sas.RefPrestashop = 18 and sas.id_product_attribute = 2506;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 819.74, sas.DateModification = NOW() where sas.RefPrestashop = 18 and sas.id_product_attribute = 2507;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 875.01, sas.DateModification = NOW() where sas.RefPrestashop = 18 and sas.id_product_attribute = 2508;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 966.72, sas.DateModification = NOW() where sas.RefPrestashop = 18 and sas.id_product_attribute = 2509;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 1053.24, sas.DateModification = NOW() where sas.RefPrestashop = 18 and sas.id_product_attribute = 2510;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 1185.65, sas.DateModification = NOW() where sas.RefPrestashop = 18 and sas.id_product_attribute = 2511;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 1061.01, sas.DateModification = NOW() where sas.RefPrestashop = 18 and sas.id_product_attribute = 2512;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 1312.08, sas.DateModification = NOW() where sas.RefPrestashop = 18 and sas.id_product_attribute = 2513;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 1471.25, sas.DateModification = NOW() where sas.RefPrestashop = 18 and sas.id_product_attribute = 2514;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 1506.56, sas.DateModification = NOW() where sas.RefPrestashop = 18 and sas.id_product_attribute = 2515;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 1626.4, sas.DateModification = NOW() where sas.RefPrestashop = 18 and sas.id_product_attribute = 2516;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 1631.75, sas.DateModification = NOW() where sas.RefPrestashop = 18 and sas.id_product_attribute = 2517;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 1.3, sas.DateModification = NOW() where sas.RefPrestashop = 27 and sas.id_product_attribute = 447;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 236.38, sas.DateModification = NOW() where sas.RefPrestashop = 29 and sas.id_product_attribute = 372;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 288.25, sas.DateModification = NOW() where sas.RefPrestashop = 29 and sas.id_product_attribute = 373;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 293.07, sas.DateModification = NOW() where sas.RefPrestashop = 29 and sas.id_product_attribute = 374;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 344.87, sas.DateModification = NOW() where sas.RefPrestashop = 29 and sas.id_product_attribute = 375;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 466.16, sas.DateModification = NOW() where sas.RefPrestashop = 29 and sas.id_product_attribute = 376;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 524.22, sas.DateModification = NOW() where sas.RefPrestashop = 29 and sas.id_product_attribute = 377;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 588.35, sas.DateModification = NOW() where sas.RefPrestashop = 29 and sas.id_product_attribute = 378;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 613.76, sas.DateModification = NOW() where sas.RefPrestashop = 29 and sas.id_product_attribute = 379;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 695.78, sas.DateModification = NOW() where sas.RefPrestashop = 29 and sas.id_product_attribute = 380;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 814.24, sas.DateModification = NOW() where sas.RefPrestashop = 29 and sas.id_product_attribute = 381;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 856.8, sas.DateModification = NOW() where sas.RefPrestashop = 29 and sas.id_product_attribute = 382;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 980.98, sas.DateModification = NOW() where sas.RefPrestashop = 29 and sas.id_product_attribute = 383;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 1233.12, sas.DateModification = NOW() where sas.RefPrestashop = 29 and sas.id_product_attribute = 384;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 1277.92, sas.DateModification = NOW() where sas.RefPrestashop = 29 and sas.id_product_attribute = 385;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 801.52, sas.DateModification = NOW() where sas.RefPrestashop = 122 and sas.id_product_attribute = 2456;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 18.46, sas.DateModification = NOW() where sas.RefPrestashop = 149 and sas.id_product_attribute = 466;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 21.44, sas.DateModification = NOW() where sas.RefPrestashop = 149 and sas.id_product_attribute = 467;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 389.71, sas.DateModification = NOW() where sas.RefPrestashop = 151 and sas.id_product_attribute = 339;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 422.23, sas.DateModification = NOW() where sas.RefPrestashop = 151 and sas.id_product_attribute = 340;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 485.07, sas.DateModification = NOW() where sas.RefPrestashop = 151 and sas.id_product_attribute = 341;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 527.98, sas.DateModification = NOW() where sas.RefPrestashop = 151 and sas.id_product_attribute = 342;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 0.0612, sas.DateModification = NOW() where sas.RefPrestashop = 153 and sas.id_product_attribute = 417;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 0.08559, sas.DateModification = NOW() where sas.RefPrestashop = 153 and sas.id_product_attribute = 419;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 0.12231, sas.DateModification = NOW() where sas.RefPrestashop = 153 and sas.id_product_attribute = 422;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 0.15274, sas.DateModification = NOW() where sas.RefPrestashop = 153 and sas.id_product_attribute = 425;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 0.18346, sas.DateModification = NOW() where sas.RefPrestashop = 153 and sas.id_product_attribute = 428;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 0.21989, sas.DateModification = NOW() where sas.RefPrestashop = 153 and sas.id_product_attribute = 429;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 0.24447, sas.DateModification = NOW() where sas.RefPrestashop = 153 and sas.id_product_attribute = 430;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 0.30562, sas.DateModification = NOW() where sas.RefPrestashop = 153 and sas.id_product_attribute = 431;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 1112.77, sas.DateModification = NOW() where sas.RefPrestashop = 154 and sas.id_product_attribute = 2367;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 1331.26, sas.DateModification = NOW() where sas.RefPrestashop = 154 and sas.id_product_attribute = 2368;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 2225.53, sas.DateModification = NOW() where sas.RefPrestashop = 154 and sas.id_product_attribute = 2369;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 2662.53, sas.DateModification = NOW() where sas.RefPrestashop = 154 and sas.id_product_attribute = 2370;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 4451.06, sas.DateModification = NOW() where sas.RefPrestashop = 154 and sas.id_product_attribute = 2371;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 5325.05, sas.DateModification = NOW() where sas.RefPrestashop = 154 and sas.id_product_attribute = 2372;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 8902.12, sas.DateModification = NOW() where sas.RefPrestashop = 154 and sas.id_product_attribute = 2373;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 307.76, sas.DateModification = NOW() where sas.RefPrestashop = 158 and sas.id_product_attribute = 2518;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 392.34, sas.DateModification = NOW() where sas.RefPrestashop = 158 and sas.id_product_attribute = 2519;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 466.78, sas.DateModification = NOW() where sas.RefPrestashop = 158 and sas.id_product_attribute = 2520;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 622.8, sas.DateModification = NOW() where sas.RefPrestashop = 158 and sas.id_product_attribute = 2521;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 762.1, sas.DateModification = NOW() where sas.RefPrestashop = 158 and sas.id_product_attribute = 2522;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 697.25, sas.DateModification = NOW() where sas.RefPrestashop = 158 and sas.id_product_attribute = 2523;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 853.27, sas.DateModification = NOW() where sas.RefPrestashop = 158 and sas.id_product_attribute = 2524;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 927.72, sas.DateModification = NOW() where sas.RefPrestashop = 158 and sas.id_product_attribute = 2525;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 1083.74, sas.DateModification = NOW() where sas.RefPrestashop = 158 and sas.id_product_attribute = 2526;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 1383.49, sas.DateModification = NOW() where sas.RefPrestashop = 158 and sas.id_product_attribute = 2527;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 1579.81, sas.DateModification = NOW() where sas.RefPrestashop = 158 and sas.id_product_attribute = 2528;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 1476.03, sas.DateModification = NOW() where sas.RefPrestashop = 158 and sas.id_product_attribute = 2529;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 1828.84, sas.DateModification = NOW() where sas.RefPrestashop = 158 and sas.id_product_attribute = 2530;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 1977.73, sas.DateModification = NOW() where sas.RefPrestashop = 158 and sas.id_product_attribute = 2531;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 2145.41, sas.DateModification = NOW() where sas.RefPrestashop = 158 and sas.id_product_attribute = 2532;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 1034.57, sas.DateModification = NOW() where sas.RefPrestashop = 158 and sas.id_product_attribute = 2533;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 933.57, sas.DateModification = NOW() where sas.RefPrestashop = 158 and sas.id_product_attribute = 2534;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 1327.14, sas.DateModification = NOW() where sas.RefPrestashop = 158 and sas.id_product_attribute = 2535;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 2035.66, sas.DateModification = NOW() where sas.RefPrestashop = 158 and sas.id_product_attribute = 2536;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 2099.23, sas.DateModification = NOW() where sas.RefPrestashop = 158 and sas.id_product_attribute = 2537;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 0.468, sas.DateModification = NOW() where sas.RefPrestashop = 440 and sas.id_product_attribute = 450;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 0.962, sas.DateModification = NOW() where sas.RefPrestashop = 440 and sas.id_product_attribute = 451;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 0.637, sas.DateModification = NOW() where sas.RefPrestashop = 441 and sas.id_product_attribute = 453;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 1.066, sas.DateModification = NOW() where sas.RefPrestashop = 441 and sas.id_product_attribute = 454;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 0.4407, sas.DateModification = NOW() where sas.RefPrestashop = 442 and sas.id_product_attribute = 456;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 0.84851, sas.DateModification = NOW() where sas.RefPrestashop = 442 and sas.id_product_attribute = 457;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 9.08, sas.DateModification = NOW() where sas.RefPrestashop = 465 and sas.id_product_attribute = 534;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 12.04, sas.DateModification = NOW() where sas.RefPrestashop = 465 and sas.id_product_attribute = 535;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 718.05, sas.DateModification = NOW() where sas.RefPrestashop = 511 and sas.id_product_attribute = 2475;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 888.31, sas.DateModification = NOW() where sas.RefPrestashop = 511 and sas.id_product_attribute = 2476;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 1016.88, sas.DateModification = NOW() where sas.RefPrestashop = 511 and sas.id_product_attribute = 2477;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 1277.27, sas.DateModification = NOW() where sas.RefPrestashop = 511 and sas.id_product_attribute = 2478;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 1394.85, sas.DateModification = NOW() where sas.RefPrestashop = 511 and sas.id_product_attribute = 2479;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 1355.6, sas.DateModification = NOW() where sas.RefPrestashop = 511 and sas.id_product_attribute = 2480;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 1665.24, sas.DateModification = NOW() where sas.RefPrestashop = 511 and sas.id_product_attribute = 2481;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 1827.37, sas.DateModification = NOW() where sas.RefPrestashop = 511 and sas.id_product_attribute = 2482;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 1743.58, sas.DateModification = NOW() where sas.RefPrestashop = 511 and sas.id_product_attribute = 2483;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 1903.48, sas.DateModification = NOW() where sas.RefPrestashop = 511 and sas.id_product_attribute = 2484;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 2311.53, sas.DateModification = NOW() where sas.RefPrestashop = 511 and sas.id_product_attribute = 2485;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 2765.46, sas.DateModification = NOW() where sas.RefPrestashop = 511 and sas.id_product_attribute = 2486;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 3140.91, sas.DateModification = NOW() where sas.RefPrestashop = 511 and sas.id_product_attribute = 2487;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 3297.58, sas.DateModification = NOW() where sas.RefPrestashop = 511 and sas.id_product_attribute = 2488;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 3442.46, sas.DateModification = NOW() where sas.RefPrestashop = 511 and sas.id_product_attribute = 2489;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 1808.58, sas.DateModification = NOW() where sas.RefPrestashop = 511 and sas.id_product_attribute = 2490;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 2380.37, sas.DateModification = NOW() where sas.RefPrestashop = 511 and sas.id_product_attribute = 2491;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 2537.05, sas.DateModification = NOW() where sas.RefPrestashop = 511 and sas.id_product_attribute = 2492;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 3337.67, sas.DateModification = NOW() where sas.RefPrestashop = 511 and sas.id_product_attribute = 2493;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 3626.43, sas.DateModification = NOW() where sas.RefPrestashop = 511 and sas.id_product_attribute = 2494;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 10.75, sas.DateModification = NOW() where sas.RefPrestashop = 526 and sas.id_product_attribute = 724;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 8.51, sas.DateModification = NOW() where sas.RefPrestashop = 526 and sas.id_product_attribute = 725;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 899.22, sas.DateModification = NOW() where sas.RefPrestashop = 532 and sas.id_product_attribute = 896;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 983.52, sas.DateModification = NOW() where sas.RefPrestashop = 532 and sas.id_product_attribute = 897;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 903.12, sas.DateModification = NOW() where sas.RefPrestashop = 532 and sas.id_product_attribute = 898;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 1011.62, sas.DateModification = NOW() where sas.RefPrestashop = 532 and sas.id_product_attribute = 899;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 953.64, sas.DateModification = NOW() where sas.RefPrestashop = 532 and sas.id_product_attribute = 900;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 1057.51, sas.DateModification = NOW() where sas.RefPrestashop = 532 and sas.id_product_attribute = 901;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 980.22, sas.DateModification = NOW() where sas.RefPrestashop = 532 and sas.id_product_attribute = 906;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 1092.44, sas.DateModification = NOW() where sas.RefPrestashop = 532 and sas.id_product_attribute = 907;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 978.07, sas.DateModification = NOW() where sas.RefPrestashop = 532 and sas.id_product_attribute = 908;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 1109.69, sas.DateModification = NOW() where sas.RefPrestashop = 532 and sas.id_product_attribute = 909;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 1053.5, sas.DateModification = NOW() where sas.RefPrestashop = 532 and sas.id_product_attribute = 910;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 1158.18, sas.DateModification = NOW() where sas.RefPrestashop = 532 and sas.id_product_attribute = 911;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 993.3, sas.DateModification = NOW() where sas.RefPrestashop = 532 and sas.id_product_attribute = 916;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 1098.02, sas.DateModification = NOW() where sas.RefPrestashop = 532 and sas.id_product_attribute = 917;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 1008.55, sas.DateModification = NOW() where sas.RefPrestashop = 532 and sas.id_product_attribute = 918;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 1120.54, sas.DateModification = NOW() where sas.RefPrestashop = 532 and sas.id_product_attribute = 919;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 1063.58, sas.DateModification = NOW() where sas.RefPrestashop = 532 and sas.id_product_attribute = 920;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 1159.37, sas.DateModification = NOW() where sas.RefPrestashop = 532 and sas.id_product_attribute = 921;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 1263.13, sas.DateModification = NOW() where sas.RefPrestashop = 532 and sas.id_product_attribute = 937;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 1362.38, sas.DateModification = NOW() where sas.RefPrestashop = 532 and sas.id_product_attribute = 939;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 1357.64, sas.DateModification = NOW() where sas.RefPrestashop = 532 and sas.id_product_attribute = 941;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 12.91, sas.DateModification = NOW() where sas.RefPrestashop = 536 and sas.id_product_attribute = 934;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 863.14, sas.DateModification = NOW() where sas.RefPrestashop = 558 and sas.id_product_attribute = 2335;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 864.45, sas.DateModification = NOW() where sas.RefPrestashop = 558 and sas.id_product_attribute = 2336;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 1089.25, sas.DateModification = NOW() where sas.RefPrestashop = 558 and sas.id_product_attribute = 2337;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 1227.63, sas.DateModification = NOW() where sas.RefPrestashop = 558 and sas.id_product_attribute = 2338;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 1341.65, sas.DateModification = NOW() where sas.RefPrestashop = 558 and sas.id_product_attribute = 2339;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 1372.42, sas.DateModification = NOW() where sas.RefPrestashop = 558 and sas.id_product_attribute = 2340;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 1457.47, sas.DateModification = NOW() where sas.RefPrestashop = 558 and sas.id_product_attribute = 2341;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 1522.33, sas.DateModification = NOW() where sas.RefPrestashop = 558 and sas.id_product_attribute = 2342;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 1669.98, sas.DateModification = NOW() where sas.RefPrestashop = 558 and sas.id_product_attribute = 2343;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 1875.39, sas.DateModification = NOW() where sas.RefPrestashop = 558 and sas.id_product_attribute = 2344;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 2011, sas.DateModification = NOW() where sas.RefPrestashop = 558 and sas.id_product_attribute = 2345;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 2137.45, sas.DateModification = NOW() where sas.RefPrestashop = 558 and sas.id_product_attribute = 2346;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 2011.15, sas.DateModification = NOW() where sas.RefPrestashop = 558 and sas.id_product_attribute = 2347;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 2422.5, sas.DateModification = NOW() where sas.RefPrestashop = 558 and sas.id_product_attribute = 2348;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 2511.38, sas.DateModification = NOW() where sas.RefPrestashop = 558 and sas.id_product_attribute = 2349;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 2626.53, sas.DateModification = NOW() where sas.RefPrestashop = 558 and sas.id_product_attribute = 2350;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 0.85232, sas.DateModification = NOW() where sas.RefPrestashop = 560 and sas.id_product_attribute = 1514;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 1.13643, sas.DateModification = NOW() where sas.RefPrestashop = 560 and sas.id_product_attribute = 1516;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 1.42054, sas.DateModification = NOW() where sas.RefPrestashop = 560 and sas.id_product_attribute = 1517;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 0.72, sas.DateModification = NOW() where sas.RefPrestashop = 560 and sas.id_product_attribute = 2553;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 36.67, sas.DateModification = NOW() where sas.RefPrestashop = 562 and sas.id_product_attribute = 1550;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 36.67, sas.DateModification = NOW() where sas.RefPrestashop = 562 and sas.id_product_attribute = 1551;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 41.36, sas.DateModification = NOW() where sas.RefPrestashop = 562 and sas.id_product_attribute = 1552;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 54.52, sas.DateModification = NOW() where sas.RefPrestashop = 562 and sas.id_product_attribute = 1553;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 41.08, sas.DateModification = NOW() where sas.RefPrestashop = 562 and sas.id_product_attribute = 1554;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 64.43, sas.DateModification = NOW() where sas.RefPrestashop = 562 and sas.id_product_attribute = 1555;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 73.67, sas.DateModification = NOW() where sas.RefPrestashop = 562 and sas.id_product_attribute = 1556;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 75.36, sas.DateModification = NOW() where sas.RefPrestashop = 562 and sas.id_product_attribute = 1557;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 90.47, sas.DateModification = NOW() where sas.RefPrestashop = 562 and sas.id_product_attribute = 1558;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 103.34, sas.DateModification = NOW() where sas.RefPrestashop = 562 and sas.id_product_attribute = 1559;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 54.52, sas.DateModification = NOW() where sas.RefPrestashop = 562 and sas.id_product_attribute = 1560;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 96.85, sas.DateModification = NOW() where sas.RefPrestashop = 562 and sas.id_product_attribute = 1561;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 103.84, sas.DateModification = NOW() where sas.RefPrestashop = 562 and sas.id_product_attribute = 1562;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 103.84, sas.DateModification = NOW() where sas.RefPrestashop = 562 and sas.id_product_attribute = 1563;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 109.28, sas.DateModification = NOW() where sas.RefPrestashop = 562 and sas.id_product_attribute = 1564;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 119.77, sas.DateModification = NOW() where sas.RefPrestashop = 562 and sas.id_product_attribute = 1565;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 717.74, sas.DateModification = NOW() where sas.RefPrestashop = 563 and sas.id_product_attribute = 2351;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 915.38, sas.DateModification = NOW() where sas.RefPrestashop = 563 and sas.id_product_attribute = 2352;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 982.77, sas.DateModification = NOW() where sas.RefPrestashop = 563 and sas.id_product_attribute = 2353;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 1143.3, sas.DateModification = NOW() where sas.RefPrestashop = 563 and sas.id_product_attribute = 2354;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 1240.51, sas.DateModification = NOW() where sas.RefPrestashop = 563 and sas.id_product_attribute = 2355;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 1278.34, sas.DateModification = NOW() where sas.RefPrestashop = 563 and sas.id_product_attribute = 2356;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 1350.78, sas.DateModification = NOW() where sas.RefPrestashop = 563 and sas.id_product_attribute = 2357;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 1415.1, sas.DateModification = NOW() where sas.RefPrestashop = 563 and sas.id_product_attribute = 2358;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 1553.24, sas.DateModification = NOW() where sas.RefPrestashop = 563 and sas.id_product_attribute = 2359;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 1767.62, sas.DateModification = NOW() where sas.RefPrestashop = 563 and sas.id_product_attribute = 2360;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 1925.76, sas.DateModification = NOW() where sas.RefPrestashop = 563 and sas.id_product_attribute = 2361;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 2037.34, sas.DateModification = NOW() where sas.RefPrestashop = 563 and sas.id_product_attribute = 2362;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 1894.7, sas.DateModification = NOW() where sas.RefPrestashop = 563 and sas.id_product_attribute = 2363;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 2318.75, sas.DateModification = NOW() where sas.RefPrestashop = 563 and sas.id_product_attribute = 2364;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 2397.11, sas.DateModification = NOW() where sas.RefPrestashop = 563 and sas.id_product_attribute = 2365;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 2495.67, sas.DateModification = NOW() where sas.RefPrestashop = 563 and sas.id_product_attribute = 2366;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 62.5, sas.DateModification = NOW() where sas.RefPrestashop = 572 and sas.id_product_attribute = 2446;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 120, sas.DateModification = NOW() where sas.RefPrestashop = 572 and sas.id_product_attribute = 2447;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 32, sas.DateModification = NOW() where sas.RefPrestashop = 572 and sas.id_product_attribute = 2449;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 0.79454, sas.DateModification = NOW() where sas.RefPrestashop = 577 and sas.id_product_attribute = 2538;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 0.73778, sas.DateModification = NOW() where sas.RefPrestashop = 577 and sas.id_product_attribute = 2539;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 0.70984, sas.DateModification = NOW() where sas.RefPrestashop = 577 and sas.id_product_attribute = 2540;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 0.68189, sas.DateModification = NOW() where sas.RefPrestashop = 577 and sas.id_product_attribute = 2554;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 2603.44, sas.DateModification = NOW() where sas.RefPrestashop = 578 and sas.id_product_attribute = 2561;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 3216.75, sas.DateModification = NOW() where sas.RefPrestashop = 578 and sas.id_product_attribute = 2562;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 3471.25, sas.DateModification = NOW() where sas.RefPrestashop = 578 and sas.id_product_attribute = 2563;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 4288.99, sas.DateModification = NOW() where sas.RefPrestashop = 578 and sas.id_product_attribute = 2564;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 4339.05, sas.DateModification = NOW() where sas.RefPrestashop = 578 and sas.id_product_attribute = 2565;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 5361.24, sas.DateModification = NOW() where sas.RefPrestashop = 578 and sas.id_product_attribute = 2566;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 5206.87, sas.DateModification = NOW() where sas.RefPrestashop = 578 and sas.id_product_attribute = 2567;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 6433.49, sas.DateModification = NOW() where sas.RefPrestashop = 578 and sas.id_product_attribute = 2568;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 6942.49, sas.DateModification = NOW() where sas.RefPrestashop = 578 and sas.id_product_attribute = 2569;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 8577.99, sas.DateModification = NOW() where sas.RefPrestashop = 578 and sas.id_product_attribute = 2570;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 8678.12, sas.DateModification = NOW() where sas.RefPrestashop = 578 and sas.id_product_attribute = 2571;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 10722.49, sas.DateModification = NOW() where sas.RefPrestashop = 578 and sas.id_product_attribute = 2572;
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 47.61, sas.DateModification = NOW() where sas.RefPrestashop = 588 and sas.id_product_attribute = 2581;