UPDATE saskitps_product_shop p set p.price = 38.8, p.date_upd=now() where p.id_product = 12 ;
UPDATE saskitps_product_shop p set p.price = 38.37, p.date_upd=now() where p.id_product = 15 ;
UPDATE saskitps_product_shop p set p.price = 34.53, p.date_upd=now() where p.id_product = 16 ;
UPDATE saskitps_product_shop p set p.price = 4.94, p.date_upd=now() where p.id_product = 56 ;
UPDATE saskitps_product_shop p set p.price = 4.18, p.date_upd=now() where p.id_product = 58 ;
UPDATE saskitps_product_shop p set p.price = 32.48, p.date_upd=now() where p.id_product = 63 ;
UPDATE saskitps_product_shop p set p.price = 55.83, p.date_upd=now() where p.id_product = 64 ;
UPDATE saskitps_product_shop p set p.price = 165, p.date_upd=now() where p.id_product = 96 ;
UPDATE saskitps_product_shop p set p.price = 4.87, p.date_upd=now() where p.id_product = 97 ;
UPDATE saskitps_product_shop p set p.price = 4.94, p.date_upd=now() where p.id_product = 98 ;
UPDATE saskitps_product_shop p set p.price = 97.13, p.date_upd=now() where p.id_product = 99 ;
UPDATE saskitps_product_shop p set p.price = 111.83, p.date_upd=now() where p.id_product = 100 ;
UPDATE saskitps_product_shop p set p.price = 182.76, p.date_upd=now() where p.id_product = 114 ;
UPDATE saskitps_product_shop p set p.price = 124, p.date_upd=now() where p.id_product = 115 ;
UPDATE saskitps_product_shop p set p.price = 168, p.date_upd=now() where p.id_product = 116 ;
UPDATE saskitps_product_shop p set p.price = 54, p.date_upd=now() where p.id_product = 118 ;
UPDATE saskitps_product_shop p set p.price = 715, p.date_upd=now() where p.id_product = 121 ;
UPDATE saskitps_product_shop p set p.price = 187, p.date_upd=now() where p.id_product = 124 ;
UPDATE saskitps_product_shop p set p.price = 107.62, p.date_upd=now() where p.id_product = 125 ;
UPDATE saskitps_product_shop p set p.price = 71.05, p.date_upd=now() where p.id_product = 126 ;
UPDATE saskitps_product_shop p set p.price = 100.31, p.date_upd=now() where p.id_product = 127 ;
UPDATE saskitps_product_shop p set p.price = 6.34, p.date_upd=now() where p.id_product = 131 ;
UPDATE saskitps_product_shop p set p.price = 47.94, p.date_upd=now() where p.id_product = 137 ;
UPDATE saskitps_product_shop p set p.price = 594.83, p.date_upd=now() where p.id_product = 138 ;
UPDATE saskitps_product_shop p set p.price = 640.38, p.date_upd=now() where p.id_product = 139 ;
UPDATE saskitps_product_shop p set p.price = 41.1, p.date_upd=now() where p.id_product = 140 ;
UPDATE saskitps_product_shop p set p.price = 3811.14, p.date_upd=now() where p.id_product = 141 ;
UPDATE saskitps_product_shop p set p.price = 119.89, p.date_upd=now() where p.id_product = 142 ;
UPDATE saskitps_product_shop p set p.price = 138.13, p.date_upd=now() where p.id_product = 143 ;
UPDATE saskitps_product_shop p set p.price = 191.42, p.date_upd=now() where p.id_product = 144 ;
UPDATE saskitps_product_shop p set p.price = 237.1, p.date_upd=now() where p.id_product = 145 ;
UPDATE saskitps_product_shop p set p.price = 315.06, p.date_upd=now() where p.id_product = 146 ;
UPDATE saskitps_product_shop p set p.price = 431.65, p.date_upd=now() where p.id_product = 147 ;
UPDATE saskitps_product_shop p set p.price = 441.73, p.date_upd=now() where p.id_product = 148 ;
UPDATE saskitps_product_shop p set p.price = 16.5, p.date_upd=now() where p.id_product = 188 ;
UPDATE saskitps_product_shop p set p.price = 12.1, p.date_upd=now() where p.id_product = 189 ;
UPDATE saskitps_product_shop p set p.price = 9.9, p.date_upd=now() where p.id_product = 190 ;
UPDATE saskitps_product_shop p set p.price = 3.77, p.date_upd=now() where p.id_product = 445 ;
UPDATE saskitps_product_shop p set p.price = 10.26, p.date_upd=now() where p.id_product = 447 ;
UPDATE saskitps_product_shop p set p.price = 7.44, p.date_upd=now() where p.id_product = 448 ;
UPDATE saskitps_product_shop p set p.price = 19.32, p.date_upd=now() where p.id_product = 449 ;
UPDATE saskitps_product_shop p set p.price = 120, p.date_upd=now() where p.id_product = 450 ;
UPDATE saskitps_product_shop p set p.price = 1.1, p.date_upd=now() where p.id_product = 453 ;
UPDATE saskitps_product_shop p set p.price = 524.71, p.date_upd=now() where p.id_product = 459 ;
UPDATE saskitps_product_shop p set p.price = 59.85, p.date_upd=now() where p.id_product = 463 ;
UPDATE saskitps_product_shop p set p.price = 2.25, p.date_upd=now() where p.id_product = 466 ;
UPDATE saskitps_product_shop p set p.price = 1.87, p.date_upd=now() where p.id_product = 467 ;
UPDATE saskitps_product_shop p set p.price = 2.91, p.date_upd=now() where p.id_product = 468 ;
UPDATE saskitps_product_shop p set p.price = 2.56, p.date_upd=now() where p.id_product = 469 ;
UPDATE saskitps_product_shop p set p.price = 86.26, p.date_upd=now() where p.id_product = 479 ;
UPDATE saskitps_product_shop p set p.price = 0.97, p.date_upd=now() where p.id_product = 483 ;
UPDATE saskitps_product_shop p set p.price = 1.77, p.date_upd=now() where p.id_product = 484 ;
UPDATE saskitps_product_shop p set p.price = 1.02, p.date_upd=now() where p.id_product = 485 ;
UPDATE saskitps_product_shop p set p.price = 9.43, p.date_upd=now() where p.id_product = 487 ;
UPDATE saskitps_product_shop p set p.price = 25.14, p.date_upd=now() where p.id_product = 508 ;
UPDATE saskitps_product_shop p set p.price = 2.25, p.date_upd=now() where p.id_product = 512 ;
UPDATE saskitps_product_shop p set p.price = 1.87, p.date_upd=now() where p.id_product = 513 ;
UPDATE saskitps_product_shop p set p.price = 2.31, p.date_upd=now() where p.id_product = 514 ;
UPDATE saskitps_product_shop p set p.price = 2.31, p.date_upd=now() where p.id_product = 515 ;
UPDATE saskitps_product_shop p set p.price = 3.54, p.date_upd=now() where p.id_product = 516 ;
UPDATE saskitps_product_shop p set p.price = 2.85, p.date_upd=now() where p.id_product = 517 ;
UPDATE saskitps_product_shop p set p.price = 11.02, p.date_upd=now() where p.id_product = 518 ;
UPDATE saskitps_product_shop p set p.price = 11.03, p.date_upd=now() where p.id_product = 519 ;
UPDATE saskitps_product_shop p set p.price = 1.34, p.date_upd=now() where p.id_product = 520 ;
UPDATE saskitps_product_shop p set p.price = 3.44, p.date_upd=now() where p.id_product = 522 ;
UPDATE saskitps_product_shop p set p.price = 3.22, p.date_upd=now() where p.id_product = 523 ;
UPDATE saskitps_product_shop p set p.price = 24.03, p.date_upd=now() where p.id_product = 524 ;
UPDATE saskitps_product_shop p set p.price = 1.18, p.date_upd=now() where p.id_product = 527 ;
UPDATE saskitps_product_shop p set p.price = 8.23, p.date_upd=now() where p.id_product = 538 ;
UPDATE saskitps_product_shop p set p.price = 139.17, p.date_upd=now() where p.id_product = 548 ;
UPDATE saskitps_product_shop p set p.price = 11.27, p.date_upd=now() where p.id_product = 549 ;
UPDATE saskitps_product_shop p set p.price = 13.19, p.date_upd=now() where p.id_product = 550 ;
UPDATE saskitps_product_shop p set p.price = 13.19, p.date_upd=now() where p.id_product = 551 ;
UPDATE saskitps_product_shop p set p.price = 29.78, p.date_upd=now() where p.id_product = 552 ;
UPDATE saskitps_product_shop p set p.price = 90.27, p.date_upd=now() where p.id_product = 559 ;

UPDATE saskitps_product p set p.price = 339.9942, p.date_upd=now() where p.id_product = 18 ;

UPDATE saskitps_product_shop p set p.price = 320.000000, p.date_upd=now() where p.id_product = 18 ;
UPDATE saskitps_product_shop p set p.price = 0.800000, p.date_upd=now() where p.id_product = 27 ;
UPDATE saskitps_product_shop p set p.price = 204.000000, p.date_upd=now() where p.id_product = 29 ;
UPDATE saskitps_product_shop p set p.price = 761.000000, p.date_upd=now() where p.id_product = 122 ;
UPDATE saskitps_product_shop p set p.price = 15.960000, p.date_upd=now() where p.id_product = 149 ;
UPDATE saskitps_product_shop p set p.price = 383.280000, p.date_upd=now() where p.id_product = 151 ;
UPDATE saskitps_product_shop p set p.price = 0.055700, p.date_upd=now() where p.id_product = 153 ;
UPDATE saskitps_product_shop p set p.price = 1018.000000, p.date_upd=now() where p.id_product = 154 ;
UPDATE saskitps_product_shop p set p.price = 247.000000, p.date_upd=now() where p.id_product = 158 ;
UPDATE saskitps_product_shop p set p.price = 0.460000, p.date_upd=now() where p.id_product = 440 ;
UPDATE saskitps_product_shop p set p.price = 0.640000, p.date_upd=now() where p.id_product = 441 ;
UPDATE saskitps_product_shop p set p.price = 0.400000, p.date_upd=now() where p.id_product = 442 ;
UPDATE saskitps_product_shop p set p.price = 8.380000, p.date_upd=now() where p.id_product = 465 ;
UPDATE saskitps_product_shop p set p.price = 505.500000, p.date_upd=now() where p.id_product = 511 ;
UPDATE saskitps_product_shop p set p.price = 8.180000, p.date_upd=now() where p.id_product = 526 ;
UPDATE saskitps_product_shop p set p.price = 884.970000, p.date_upd=now() where p.id_product = 532 ;
UPDATE saskitps_product_shop p set p.price = 7.830000, p.date_upd=now() where p.id_product = 536 ;
UPDATE saskitps_product_shop p set p.price = 838.600000, p.date_upd=now() where p.id_product = 558 ;
UPDATE saskitps_product_shop p set p.price = 0.660000, p.date_upd=now() where p.id_product = 560 ;
UPDATE saskitps_product_shop p set p.price = 35.000000, p.date_upd=now() where p.id_product = 562 ;
UPDATE saskitps_product_shop p set p.price = 35.000000, p.date_upd=now() where p.id_product = 562 ;
UPDATE saskitps_product_shop p set p.price = 697.000000, p.date_upd=now() where p.id_product = 563 ;
UPDATE saskitps_product_shop p set p.price = 769.500000, p.date_upd=now() where p.id_product = 571 ;
UPDATE saskitps_product_shop p set p.price = 29.750000, p.date_upd=now() where p.id_product = 572 ;
UPDATE saskitps_product_shop p set p.price = 82.500000, p.date_upd=now() where p.id_product = 574 ;
UPDATE saskitps_product_shop p set p.price = 0.590000, p.date_upd=now() where p.id_product = 577 ;
UPDATE saskitps_product_shop p set p.price = 2263.860000, p.date_upd=now() where p.id_product = 578 ;

UPDATE saskitps_product p set p.price = 49, p.date_upd=now() where p.id_product = 12 ;	
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 49, sas.DateModification = NOW() where sas.RefPrestashop = 12 ;
	
UPDATE saskitps_product p set p.price = 21.32, p.date_upd=now() where p.id_product = 14 ;	
UPDATE TSaskit sas set sas.OldPrix = sas.PrixMagasin, sas.PrixMagasin = 21.32, sas.DateModification = NOW() where sas.RefPrestashop = 14 ;

UPDATE saskitps_product_attribute_shop pa set pa.price = 0 where pa.id_product = 18 and pa.id_product_attribute = 2495 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 67 where pa.id_product = 18 and pa.id_product_attribute = 2496 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 147 where pa.id_product = 18 and pa.id_product_attribute = 2497 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 197 where pa.id_product = 18 and pa.id_product_attribute = 2498 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 296 where pa.id_product = 18 and pa.id_product_attribute = 2499 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 275 where pa.id_product = 18 and pa.id_product_attribute = 2500 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 296 where pa.id_product = 18 and pa.id_product_attribute = 2502 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 443 where pa.id_product = 18 and pa.id_product_attribute = 2503 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 424 where pa.id_product = 18 and pa.id_product_attribute = 2504 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 443 where pa.id_product = 18 and pa.id_product_attribute = 2505 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 542 where pa.id_product = 18 and pa.id_product_attribute = 2506 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 450 where pa.id_product = 18 and pa.id_product_attribute = 2507 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 506 where pa.id_product = 18 and pa.id_product_attribute = 2508 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 592 where pa.id_product = 18 and pa.id_product_attribute = 2509 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 666 where pa.id_product = 18 and pa.id_product_attribute = 2510 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 797 where pa.id_product = 18 and pa.id_product_attribute = 2511 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 666 where pa.id_product = 18 and pa.id_product_attribute = 2512 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 905 where pa.id_product = 18 and pa.id_product_attribute = 2513 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 1055 where pa.id_product = 18 and pa.id_product_attribute = 2514 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 1088 where pa.id_product = 18 and pa.id_product_attribute = 2515 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 1200 where pa.id_product = 18 and pa.id_product_attribute = 2516 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 1205 where pa.id_product = 18 and pa.id_product_attribute = 2517 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 0 where pa.id_product = 27 and pa.id_product_attribute = 446 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 0.49 where pa.id_product = 27 and pa.id_product_attribute = 447 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 0 where pa.id_product = 29 and pa.id_product_attribute = 372 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 50 where pa.id_product = 29 and pa.id_product_attribute = 373 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 53 where pa.id_product = 29 and pa.id_product_attribute = 374 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 101 where pa.id_product = 29 and pa.id_product_attribute = 375 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 212 where pa.id_product = 29 and pa.id_product_attribute = 376 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 251 where pa.id_product = 29 and pa.id_product_attribute = 377 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 316 where pa.id_product = 29 and pa.id_product_attribute = 378 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 344 where pa.id_product = 29 and pa.id_product_attribute = 379 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 418 where pa.id_product = 29 and pa.id_product_attribute = 380 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 523 where pa.id_product = 29 and pa.id_product_attribute = 381 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 561 where pa.id_product = 29 and pa.id_product_attribute = 382 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 673 where pa.id_product = 29 and pa.id_product_attribute = 383 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 897 where pa.id_product = 29 and pa.id_product_attribute = 384 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 937 where pa.id_product = 29 and pa.id_product_attribute = 385 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 0 where pa.id_product = 122 and pa.id_product_attribute = 2456 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 3 where pa.id_product = 122 and pa.id_product_attribute = 2457 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 0 where pa.id_product = 149 and pa.id_product_attribute = 466 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 1.3 where pa.id_product = 149 and pa.id_product_attribute = 467 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 0 where pa.id_product = 151 and pa.id_product_attribute = 339 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 30.49 where pa.id_product = 151 and pa.id_product_attribute = 340 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 92.96 where pa.id_product = 151 and pa.id_product_attribute = 341 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 135.12 where pa.id_product = 151 and pa.id_product_attribute = 342 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 0 where pa.id_product = 153 and pa.id_product_attribute = 417 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 0.0223 where pa.id_product = 153 and pa.id_product_attribute = 419 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 0.0557 where pa.id_product = 153 and pa.id_product_attribute = 422 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 0.0835 where pa.id_product = 153 and pa.id_product_attribute = 425 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 0.1115 where pa.id_product = 153 and pa.id_product_attribute = 428 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 0.1447 where pa.id_product = 153 and pa.id_product_attribute = 429 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 0.1672 where pa.id_product = 153 and pa.id_product_attribute = 430 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 0.2229 where pa.id_product = 153 and pa.id_product_attribute = 431 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 0 where pa.id_product = 154 and pa.id_product_attribute = 2367 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 174 where pa.id_product = 154 and pa.id_product_attribute = 2368 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 1018 where pa.id_product = 154 and pa.id_product_attribute = 2369 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 1365 where pa.id_product = 154 and pa.id_product_attribute = 2370 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 3054 where pa.id_product = 154 and pa.id_product_attribute = 2371 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 3748 where pa.id_product = 154 and pa.id_product_attribute = 2372 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 7126 where pa.id_product = 154 and pa.id_product_attribute = 2373 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 0 where pa.id_product = 158 and pa.id_product_attribute = 2518 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 70 where pa.id_product = 158 and pa.id_product_attribute = 2519 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 127 where pa.id_product = 158 and pa.id_product_attribute = 2520 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 257 where pa.id_product = 158 and pa.id_product_attribute = 2521 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 397 where pa.id_product = 158 and pa.id_product_attribute = 2522 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 315 where pa.id_product = 158 and pa.id_product_attribute = 2523 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 445 where pa.id_product = 158 and pa.id_product_attribute = 2524 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 503 where pa.id_product = 158 and pa.id_product_attribute = 2525 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 633 where pa.id_product = 158 and pa.id_product_attribute = 2526 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 869 where pa.id_product = 158 and pa.id_product_attribute = 2527 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 1025 where pa.id_product = 158 and pa.id_product_attribute = 2528 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 936 where pa.id_product = 158 and pa.id_product_attribute = 2529 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 1226 where pa.id_product = 158 and pa.id_product_attribute = 2530 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 1341 where pa.id_product = 158 and pa.id_product_attribute = 2531 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 1549 where pa.id_product = 158 and pa.id_product_attribute = 2532 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 629 where pa.id_product = 158 and pa.id_product_attribute = 2533 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 501 where pa.id_product = 158 and pa.id_product_attribute = 2534 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 821 where pa.id_product = 158 and pa.id_product_attribute = 2535 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 1443 where pa.id_product = 158 and pa.id_product_attribute = 2536 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 1639 where pa.id_product = 158 and pa.id_product_attribute = 2537 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 0 where pa.id_product = 440 and pa.id_product_attribute = 450 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 0.46 where pa.id_product = 440 and pa.id_product_attribute = 451 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 0 where pa.id_product = 441 and pa.id_product_attribute = 453 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 0.27 where pa.id_product = 441 and pa.id_product_attribute = 454 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 0 where pa.id_product = 442 and pa.id_product_attribute = 456 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 0.38 where pa.id_product = 442 and pa.id_product_attribute = 457 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 0 where pa.id_product = 465 and pa.id_product_attribute = 534 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 2.39 where pa.id_product = 465 and pa.id_product_attribute = 535 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 0 where pa.id_product = 511 and pa.id_product_attribute = 2474 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 129.5 where pa.id_product = 511 and pa.id_product_attribute = 2475 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 279.5 where pa.id_product = 511 and pa.id_product_attribute = 2476 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 386.5 where pa.id_product = 511 and pa.id_product_attribute = 2477 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 615.5 where pa.id_product = 511 and pa.id_product_attribute = 2478 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 733.5 where pa.id_product = 511 and pa.id_product_attribute = 2479 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 672.5 where pa.id_product = 511 and pa.id_product_attribute = 2480 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 950.5 where pa.id_product = 511 and pa.id_product_attribute = 2481 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 1115.5 where pa.id_product = 511 and pa.id_product_attribute = 2482 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 1007.5 where pa.id_product = 511 and pa.id_product_attribute = 2483 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 1137.5 where pa.id_product = 511 and pa.id_product_attribute = 2484 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 1522.5 where pa.id_product = 511 and pa.id_product_attribute = 2485 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 1882.5 where pa.id_product = 511 and pa.id_product_attribute = 2486 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 2192.5 where pa.id_product = 511 and pa.id_product_attribute = 2487 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 2307.5 where pa.id_product = 511 and pa.id_product_attribute = 2488 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 2529.5 where pa.id_product = 511 and pa.id_product_attribute = 2489 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 1067.5 where pa.id_product = 511 and pa.id_product_attribute = 2490 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 1548.5 where pa.id_product = 511 and pa.id_product_attribute = 2491 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 1663.5 where pa.id_product = 511 and pa.id_product_attribute = 2492 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 2392.5 where pa.id_product = 511 and pa.id_product_attribute = 2493 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 2801.5 where pa.id_product = 511 and pa.id_product_attribute = 2494 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 2.1 where pa.id_product = 526 and pa.id_product_attribute = 724 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 0 where pa.id_product = 526 and pa.id_product_attribute = 725 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 0 where pa.id_product = 532 and pa.id_product_attribute = 896 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 94 where pa.id_product = 532 and pa.id_product_attribute = 897 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 4.54999999999995 where pa.id_product = 532 and pa.id_product_attribute = 898 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 112.47 where pa.id_product = 532 and pa.id_product_attribute = 899 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 52.92 where pa.id_product = 532 and pa.id_product_attribute = 900 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 158.26 where pa.id_product = 532 and pa.id_product_attribute = 901 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 81.13 where pa.id_product = 532 and pa.id_product_attribute = 906 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 202.32 where pa.id_product = 532 and pa.id_product_attribute = 907 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 79.5899999999999 where pa.id_product = 532 and pa.id_product_attribute = 908 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 210.3 where pa.id_product = 532 and pa.id_product_attribute = 909 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 153.28 where pa.id_product = 532 and pa.id_product_attribute = 910 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 258.93 where pa.id_product = 532 and pa.id_product_attribute = 911 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 94.13 where pa.id_product = 532 and pa.id_product_attribute = 916 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 208.19 where pa.id_product = 532 and pa.id_product_attribute = 917 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 109.47 where pa.id_product = 532 and pa.id_product_attribute = 918 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 221.31 where pa.id_product = 532 and pa.id_product_attribute = 919 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 163.35 where pa.id_product = 532 and pa.id_product_attribute = 920 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 260.35 where pa.id_product = 532 and pa.id_product_attribute = 921 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 363.69 where pa.id_product = 532 and pa.id_product_attribute = 937 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 463.04 where pa.id_product = 532 and pa.id_product_attribute = 939 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 458.67 where pa.id_product = 532 and pa.id_product_attribute = 941 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 0 where pa.id_product = 536 and pa.id_product_attribute = 933 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 2.519999 where pa.id_product = 536 and pa.id_product_attribute = 934 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 0 where pa.id_product = 558 and pa.id_product_attribute = 2335 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 0.0699999999999363 where pa.id_product = 558 and pa.id_product_attribute = 2336 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 225.4 where pa.id_product = 558 and pa.id_product_attribute = 2337 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 343.4 where pa.id_product = 558 and pa.id_product_attribute = 2338 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 458.4 where pa.id_product = 558 and pa.id_product_attribute = 2339 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 489.4 where pa.id_product = 558 and pa.id_product_attribute = 2340 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 573.4 where pa.id_product = 558 and pa.id_product_attribute = 2341 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 636.4 where pa.id_product = 558 and pa.id_product_attribute = 2342 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 783.4 where pa.id_product = 558 and pa.id_product_attribute = 2343 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 975.4 where pa.id_product = 558 and pa.id_product_attribute = 2344 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 1094.4 where pa.id_product = 558 and pa.id_product_attribute = 2345 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 1227.4 where pa.id_product = 558 and pa.id_product_attribute = 2346 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 1108.4 where pa.id_product = 558 and pa.id_product_attribute = 2347 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 1503.4 where pa.id_product = 558 and pa.id_product_attribute = 2348 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 1591.4 where pa.id_product = 558 and pa.id_product_attribute = 2349 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 1704.4 where pa.id_product = 558 and pa.id_product_attribute = 2350 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 0.08 where pa.id_product = 560 and pa.id_product_attribute = 1514 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 0.32 where pa.id_product = 560 and pa.id_product_attribute = 1516 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 0.57 where pa.id_product = 560 and pa.id_product_attribute = 1517 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 0 where pa.id_product = 560 and pa.id_product_attribute = 2553 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 0 where pa.id_product = 562 and pa.id_product_attribute = 1550 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 0 where pa.id_product = 562 and pa.id_product_attribute = 1551 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 5 where pa.id_product = 562 and pa.id_product_attribute = 1552 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 16 where pa.id_product = 562 and pa.id_product_attribute = 1553 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 5 where pa.id_product = 562 and pa.id_product_attribute = 1554 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 26 where pa.id_product = 562 and pa.id_product_attribute = 1555 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 35 where pa.id_product = 562 and pa.id_product_attribute = 1556 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 36 where pa.id_product = 562 and pa.id_product_attribute = 1557 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 51 where pa.id_product = 562 and pa.id_product_attribute = 1558 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 65 where pa.id_product = 562 and pa.id_product_attribute = 1559 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 16 where pa.id_product = 562 and pa.id_product_attribute = 1560 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 59 where pa.id_product = 562 and pa.id_product_attribute = 1561 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 65 where pa.id_product = 562 and pa.id_product_attribute = 1562 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 65 where pa.id_product = 562 and pa.id_product_attribute = 1563 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 70 where pa.id_product = 562 and pa.id_product_attribute = 1564 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 80 where pa.id_product = 562 and pa.id_product_attribute = 1565 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 0 where pa.id_product = 563 and pa.id_product_attribute = 2351 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 195.5 where pa.id_product = 563 and pa.id_product_attribute = 2352 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 262 where pa.id_product = 563 and pa.id_product_attribute = 2353 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 410 where pa.id_product = 563 and pa.id_product_attribute = 2354 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 505 where pa.id_product = 563 and pa.id_product_attribute = 2355 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 543 where pa.id_product = 563 and pa.id_product_attribute = 2356 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 615 where pa.id_product = 563 and pa.id_product_attribute = 2357 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 678 where pa.id_product = 563 and pa.id_product_attribute = 2358 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 811 where pa.id_product = 563 and pa.id_product_attribute = 2359 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 1019 where pa.id_product = 563 and pa.id_product_attribute = 2360 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 1163 where pa.id_product = 563 and pa.id_product_attribute = 2361 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 1279 where pa.id_product = 563 and pa.id_product_attribute = 2362 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 1143 where pa.id_product = 563 and pa.id_product_attribute = 2363 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 1554 where pa.id_product = 563 and pa.id_product_attribute = 2364 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 1631 where pa.id_product = 563 and pa.id_product_attribute = 2365 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 1728 where pa.id_product = 563 and pa.id_product_attribute = 2366 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 0 where pa.id_product = 571 and pa.id_product_attribute = 2444 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 769.5 where pa.id_product = 571 and pa.id_product_attribute = 2445 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 27.75 where pa.id_product = 572 and pa.id_product_attribute = 2446 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 80.25 where pa.id_product = 572 and pa.id_product_attribute = 2447 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 0 where pa.id_product = 572 and pa.id_product_attribute = 2449 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 82.5 where pa.id_product = 574 and pa.id_product_attribute = 2452 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 0 where pa.id_product = 574 and pa.id_product_attribute = 2453 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 0.1 where pa.id_product = 577 and pa.id_product_attribute = 2538 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 0.05 where pa.id_product = 577 and pa.id_product_attribute = 2539 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 0.02 where pa.id_product = 577 and pa.id_product_attribute = 2540 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 0 where pa.id_product = 577 and pa.id_product_attribute = 2554 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 0 where pa.id_product = 578 and pa.id_product_attribute = 2561 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 533.31 where pa.id_product = 578 and pa.id_product_attribute = 2562 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 754.62 where pa.id_product = 578 and pa.id_product_attribute = 2563 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 1465.7 where pa.id_product = 578 and pa.id_product_attribute = 2564 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 1509.23 where pa.id_product = 578 and pa.id_product_attribute = 2565 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 2398.09 where pa.id_product = 578 and pa.id_product_attribute = 2566 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 2263.85 where pa.id_product = 578 and pa.id_product_attribute = 2567 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 3330.48 where pa.id_product = 578 and pa.id_product_attribute = 2568 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 3773.09 where pa.id_product = 578 and pa.id_product_attribute = 2569 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 5195.26 where pa.id_product = 578 and pa.id_product_attribute = 2570 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 5282.33 where pa.id_product = 578 and pa.id_product_attribute = 2571 ;
UPDATE saskitps_product_attribute_shop pa set pa.price = 7060.04 where pa.id_product = 578 and pa.id_product_attribute = 2572 ;
